# 02. Input Preprocessing

이 Notebook에서는 최종 Dataset을 Transformer Token Classification 모델에 입력하기 위한 전처리 Pipeline을 설계한다.

현재까지 완료된 데이터 준비 과정은 다음과 같다.

- 7개 Log Type Dataset 생성
- Character Span Label 생성
- 데이터 품질 검증
- Synthetic Value 다양성 보강
- Template Family 기반 Train / Validation / Test Split
- Challenge Test 생성
- Training Shortcut 분석 및 보강

현재 최종 Dataset은 다음과 같다.

| Dataset | Samples |
| --- | ---: |
| Train | 43,048 |
| Validation | 4,951 |
| Test | 5,201 |
| Challenge Test | 1,000 |

이 Notebook에서는 다음 작업을 진행한다.

1. Input 구조 분석
2. 구조 신호 기반 Block 규칙 설계
3. Structure-aware Block Builder 구현
4. Block-local Character Span 재매핑
5. Tokenizer 후보 비교
6. max_length / Sliding Window 정책 결정
7. Tokenizer Alignment 및 BIO Label 생성
8. Backbone별 최종 학습 Dataset 생성

## 21. Input 구조 분석

실제 서비스에서는 사용자가 여러 종류의 개발 로그를 하나의 Text로 입력할 수 있다.

따라서 모델에 Text 전체를 바로 입력하는 것이 아니라, 먼저 의미 있는 논리적 Block 단위로 분리할 필요가 있다.

Block Builder를 설계하기 전에 현재 Train Dataset의 Sample이 실제로 어떤 구조를 가지고 있는지 분석한다.

이번 단계에서는 데이터를 수정하거나 실제 Block Dataset을 생성하지 않는다.

확인할 항목은 다음과 같다.

- Sample의 문자 길이
- Sample의 줄 수
- 여러 줄 Sample 비율
- JSON, HTTP Header, Stack Trace, PEM 등의 구조 신호
- 임시 구조 규칙 적용 시 Sample당 Block 수
- 하나의 Block으로 유지되는 Sample 비율
- Block 경계를 넘어가는 Entity 수

`log_type`은 분석 결과를 그룹화하기 위한 Metadata로만 사용한다.

실제 Block 분할 규칙에서는 `log_type`을 사용하지 않는다.

In [338]:
from pathlib import Path
from collections import Counter, defaultdict

import json
import re

import numpy as np
import pandas as pd

In [339]:
TRAIN_PATH = Path(
    "../data/processed/splits/"
    "train_augmented.jsonl"
)


def load_jsonl(path):
    records = []

    with path.open(
        "r",
        encoding="utf-8",
    ) as f:
        for line in f:
            if line.strip():
                records.append(
                    json.loads(line)
                )

    return records


train_records = load_jsonl(
    TRAIN_PATH
)


print(
    f"Train samples : "
    f"{len(train_records):,}"
)


assert len(train_records) == 43048

Train samples : 43,048

### 21.2 문자 길이 및 줄 수 분석

각 Sample의 문자 길이와 줄 수를 확인한다.

아직 Transformer Tokenizer를 선택하지 않았기 때문에 이 단계에서는 Token 수를 분석하지 않는다.

문자 수와 Token 수는 특히 Hex, Base64, 한글 문자열 등에서 크게 달라질 수 있으므로 Token 길이는 이후 실제 Tokenizer 후보를 이용해 별도로 분석한다.

In [340]:
structure_rows = []


for record in train_records:
    text = record["text"]

    line_count = (
        text.count("\n")
        + 1
    )

    structure_rows.append(
        {
            "log_type":
                record["log_type"],

            "char_length":
                len(text),

            "line_count":
                line_count,

            "is_multiline":
                line_count > 1,
        }
    )


structure_df = pd.DataFrame(
    structure_rows
)


structure_df.head()

      log_type  char_length  line_count  is_multiline
0  HTTP_ACCESS          239           1         False
1  HTTP_ACCESS          172           1         False
2  HTTP_ACCESS          233           1         False
3  HTTP_ACCESS          366           1         False
4  HTTP_ACCESS          229           1         False

In [341]:
def p50(values):
    return np.percentile(
        values,
        50,
    )


def p95(values):
    return np.percentile(
        values,
        95,
    )


def p99(values):
    return np.percentile(
        values,
        99,
    )

In [342]:
char_stats = (
    structure_df
    .groupby("log_type")[
        "char_length"
    ]
    .agg(
        samples="count",
        mean="mean",
        p50=p50,
        p95=p95,
        p99=p99,
        max="max",
    )
    .round(1)
)


char_stats

                  samples    mean     p50     p95     p99   max
log_type
APPLICATION_LOG      7028   170.1   149.0   296.0   356.0   416
ENV_CONFIG           4450   109.8    92.0   205.0   355.0   358
HTTP_ACCESS          7324   230.1   234.0   283.0   313.0   518
HTTP_HEADER          6003   151.1   141.0   227.0   241.0   266
JAVA_STACK_TRACE     5200  1599.5  1842.0  2379.1  2637.0  3043
JSON_LOG             7921   208.7   200.0   302.0   381.0   393
SYSTEM_LOG           5122   102.8   101.0   153.9   181.0   212

In [343]:
line_stats = (
    structure_df
    .groupby("log_type")[
        "line_count"
    ]
    .agg(
        samples="count",
        mean="mean",
        p50=p50,
        p95=p95,
        p99=p99,
        max="max",
    )
    .round(1)
)


line_stats

                  samples  mean   p50   p95   p99  max
log_type
APPLICATION_LOG      7028   1.1   1.0   1.0   6.0    6
ENV_CONFIG           4450   2.7   3.0   5.0   7.0    7
HTTP_ACCESS          7324   1.0   1.0   1.0   1.0    1
HTTP_HEADER          6003   4.3   4.0   5.0   5.0    5
JAVA_STACK_TRACE     5200  17.8  22.0  22.0  25.0   25
JSON_LOG             7921   1.1   1.0   1.0   6.0    6
SYSTEM_LOG           5122   1.0   1.0   1.0   1.0    1

In [344]:
multiline_stats = (
    structure_df
    .groupby("log_type")[
        "is_multiline"
    ]
    .agg(
        samples="count",
        multiline="sum",
        ratio="mean",
    )
)


multiline_stats["ratio"] = (
    multiline_stats["ratio"]
    * 100
).round(1)


multiline_stats

                  samples  multiline  ratio
log_type
APPLICATION_LOG      7028        100    1.4
ENV_CONFIG           4450       3660   82.2
HTTP_ACCESS          7324          0    0.0
HTTP_HEADER          6003       6003  100.0
JAVA_STACK_TRACE     5200       5200  100.0
JSON_LOG             7921        200    2.5
SYSTEM_LOG           5122          0    0.0

### 21.3 구조 신호 분석

실제 추론에서는 `log_type`이 제공되지 않는다.

따라서 Block Builder는 Text 자체에서 나타나는 구조 신호를 이용해야 한다.

현재 Dataset에서 다음 신호가 얼마나 존재하는지 확인한다.

- 완전한 JSON Object
- Java Stack Frame 또는 `Caused by`
- HTTP Header 형태
- HTTP Request Line
- Private Key PEM Marker
- Timestamp로 시작하는 Log Event

이 결과는 다음 단계에서 구조 기반 Block 규칙을 설계할 때 사용한다.

In [345]:
HEADER_LINE_RE = re.compile(
    r"^[A-Za-z0-9][A-Za-z0-9_-]*"
    r":\s*.*$"
)


HTTP_REQUEST_LINE_RE = re.compile(
    r"^(GET|POST|PUT|PATCH|DELETE|"
    r"HEAD|OPTIONS)\s+\S+\s+HTTP/"
)


STACK_FRAME_RE = re.compile(
    r"^\s*at\s+[\w.$]+"
)


CAUSED_BY_RE = re.compile(
    r"^\s*(?:Caused by|Suppressed):"
)


TIMESTAMP_RE = re.compile(
    r"^\s*(?:"
    r"\d{4}-\d{2}-\d{2}"
    r"|"
    r"\d{4}/\d{2}/\d{2}"
    r"|"
    r"\[?\d{1,2}/[A-Za-z]{3}/\d{4}"
    r")"
)


PEM_BEGIN_RE = re.compile(
    r"-----BEGIN "
    r"(?:RSA |EC |ENCRYPTED |OPENSSH )?"
    r"PRIVATE KEY-----"
)


PEM_END_RE = re.compile(
    r"-----END "
    r"(?:RSA |EC |ENCRYPTED |OPENSSH )?"
    r"PRIVATE KEY-----"
)

In [346]:
def is_complete_json(text):
    stripped = text.strip()

    if not (
        stripped.startswith("{")
        or stripped.startswith("[")
    ):
        return False

    try:
        value = json.loads(
            stripped
        )

        return isinstance(
            value,
            (dict, list),
        )

    except json.JSONDecodeError:
        return False

In [347]:
def detect_structure_signals(text):
    lines = text.splitlines()

    header_line_count = sum(
        bool(
            HEADER_LINE_RE.match(
                line.strip()
            )
        )
        for line in lines
        if line.strip()
    )

    has_stack_frame = any(
        STACK_FRAME_RE.match(line)
        for line in lines
    )

    has_caused_by = any(
        CAUSED_BY_RE.match(line)
        for line in lines
    )

    has_request_line = any(
        HTTP_REQUEST_LINE_RE.match(
            line.strip()
        )
        for line in lines
    )

    return {
        "is_json":
            is_complete_json(text),

        "has_stack":
            (
                has_stack_frame
                or has_caused_by
            ),

        "has_headers":
            header_line_count >= 2,

        "has_request_line":
            has_request_line,

        "has_pem":
            bool(
                PEM_BEGIN_RE.search(text)
                and PEM_END_RE.search(text)
            ),

        "starts_timestamp":
            bool(
                lines
                and TIMESTAMP_RE.match(
                    lines[0]
                )
            ),
    }

In [348]:
signal_rows = []


for record in train_records:
    signals = (
        detect_structure_signals(
            record["text"]
        )
    )

    signals[
        "log_type"
    ] = record[
        "log_type"
    ]

    signal_rows.append(
        signals
    )


signal_df = pd.DataFrame(
    signal_rows
)

In [349]:
signal_summary = (
    signal_df
    .groupby("log_type")
    .sum()
)


signal_summary

,is_json,has_stack,has_headers,has_request_line,has_pem,starts_timestamp
log_type,,,,,,
APPLICATION_LOG,0,0,0,0,100,4729
ENV_CONFIG,0,0,1305,0,470,0
HTTP_ACCESS,0,0,0,100,0,0
HTTP_HEADER,0,0,6003,5603,0,0
JAVA_STACK_TRACE,0,5200,0,0,371,0
JSON_LOG,7671,0,0,0,200,0
SYSTEM_LOG,0,0,0,0,0,0

In [350]:
signal_ratio = (
    signal_df
    .groupby("log_type")
    .mean()
    * 100
).round(1)


signal_ratio

,is_json,has_stack,has_headers,has_request_line,has_pem,starts_timestamp
log_type,,,,,,
APPLICATION_LOG,0.0,0.0,0.0,0.0,1.4,67.3
ENV_CONFIG,0.0,0.0,29.3,0.0,10.6,0.0
HTTP_ACCESS,0.0,0.0,0.0,1.4,0.0,0.0
HTTP_HEADER,0.0,0.0,100.0,93.3,0.0,0.0
JAVA_STACK_TRACE,0.0,100.0,0.0,0.0,7.1,0.0
JSON_LOG,96.8,0.0,0.0,0.0,2.5,0.0
SYSTEM_LOG,0.0,0.0,0.0,0.0,0.0,0.0

### 21.4 분석용 임시 Block 규칙

현재 Sample이 이미 하나의 논리적 Block에 가까운지 확인하기 위해 최소한의 구조 규칙을 임시로 적용한다.

이 규칙은 최종 Block Builder가 아니다.

현재 단계에서는 다음 구조가 확인되면 Sample 전체를 하나의 Block으로 유지한다.

- 완전한 JSON
- Stack Trace
- HTTP Header Block
- PEM Private Key 포함 Sample

그 외 Multiline Text에서는 Timestamp로 시작하는 새로운 줄을 새로운 Event의 시작 후보로 사용한다.

이 임시 규칙을 이용해 현재 Dataset이 실제로 몇 개의 Block으로 나뉘는지 확인한다.

In [351]:
def get_line_spans(text):
    lines = text.splitlines(
        keepends=True
    )

    spans = []

    cursor = 0

    for line in lines:
        start = cursor
        end = (
            cursor
            + len(line)
        )

        spans.append(
            {
                "text": line,
                "start": start,
                "end": end,
            }
        )

        cursor = end

    if not lines and text:
        spans.append(
            {
                "text": text,
                "start": 0,
                "end": len(text),
            }
        )

    return spans

In [352]:
def candidate_block_spans(text):
    if not text:
        return []

    signals = (
        detect_structure_signals(
            text
        )
    )

    # 구조적으로 하나의 단위가 명확한 경우
    if (
        signals["is_json"]
        or signals["has_stack"]
        or signals["has_headers"]
        or signals["has_pem"]
    ):
        return [
            (0, len(text))
        ]

    line_spans = get_line_spans(
        text
    )

    if len(line_spans) <= 1:
        return [
            (0, len(text))
        ]

    block_spans = []

    block_start = 0

    for index, line_info in enumerate(
        line_spans
    ):
        if index == 0:
            continue

        line = line_info[
            "text"
        ]

        if TIMESTAMP_RE.match(
            line
        ):
            block_end = (
                line_info[
                    "start"
                ]
            )

            if (
                block_end
                > block_start
            ):
                block_spans.append(
                    (
                        block_start,
                        block_end,
                    )
                )

            block_start = (
                line_info[
                    "start"
                ]
            )

    if block_start < len(text):
        block_spans.append(
            (
                block_start,
                len(text),
            )
        )

    return block_spans

In [353]:
block_analysis_rows = []


for record in train_records:
    block_spans = (
        candidate_block_spans(
            record["text"]
        )
    )

    block_analysis_rows.append(
        {
            "log_type":
                record["log_type"],

            "block_count":
                len(block_spans),

            "single_block":
                len(block_spans) == 1,
        }
    )


block_analysis_df = pd.DataFrame(
    block_analysis_rows
)

In [354]:
block_count_stats = (
    block_analysis_df
    .groupby("log_type")[
        "block_count"
    ]
    .agg(
        samples="count",
        mean="mean",
        p50=p50,
        p95=p95,
        p99=p99,
        max="max",
    )
    .round(2)
)


block_count_stats

                  samples  mean  p50  p95  p99  max
log_type
APPLICATION_LOG      7028   1.0  1.0  1.0  1.0    1
ENV_CONFIG           4450   1.0  1.0  1.0  1.0    1
HTTP_ACCESS          7324   1.0  1.0  1.0  1.0    1
HTTP_HEADER          6003   1.0  1.0  1.0  1.0    1
JAVA_STACK_TRACE     5200   1.0  1.0  1.0  1.0    1
JSON_LOG             7921   1.0  1.0  1.0  1.0    1
SYSTEM_LOG           5122   1.0  1.0  1.0  1.0    1

In [355]:
single_block_stats = (
    block_analysis_df
    .groupby("log_type")[
        "single_block"
    ]
    .agg(
        samples="count",
        single_block="sum",
        ratio="mean",
    )
)


single_block_stats[
    "ratio"
] = (
    single_block_stats[
        "ratio"
    ]
    * 100
).round(1)


single_block_stats

                  samples  single_block  ratio
log_type
APPLICATION_LOG      7028          7028  100.0
ENV_CONFIG           4450          4450  100.0
HTTP_ACCESS          7324          7324  100.0
HTTP_HEADER          6003          6003  100.0
JAVA_STACK_TRACE     5200          5200  100.0
JSON_LOG             7921          7921  100.0
SYSTEM_LOG           5122          5122  100.0

### 21.6 Block 경계를 넘는 Entity 분석

Entity 하나가 두 Block 사이에서 잘리면 모델은 필요한 문맥 또는 Entity Value 일부만 보게 될 수 있다.

따라서 현재 임시 Block 규칙을 적용했을 때 모든 Entity가 하나의 Block 안에 완전히 포함되는지 확인한다.

목표는 다음과 같다.

`Cross-boundary Entity = 0`

0이 아니라면 해당 Block 규칙은 그대로 사용할 수 없으며 다음 단계에서 수정해야 한다.

In [356]:
def find_entity_block(
    entity,
    block_spans,
):
    entity_start = entity[
        "start"
    ]

    entity_end = entity[
        "end"
    ]

    matching_blocks = []

    for block_index, (
        block_start,
        block_end,
    ) in enumerate(
        block_spans
    ):
        if (
            entity_start >= block_start
            and entity_end <= block_end
        ):
            matching_blocks.append(
                block_index
            )

    return matching_blocks

In [357]:
cross_boundary_entities = []
multi_matched_entities = []


for record in train_records:
    block_spans = (
        candidate_block_spans(
            record["text"]
        )
    )

    for entity in record[
        "entities"
    ]:
        matching_blocks = (
            find_entity_block(
                entity,
                block_spans,
            )
        )

        if len(matching_blocks) == 0:
            cross_boundary_entities.append(
                {
                    "sample_id":
                        record["sample_id"],

                    "log_type":
                        record["log_type"],

                    "label":
                        entity["label"],

                    "value":
                        entity["value"],
                }
            )

        elif len(matching_blocks) > 1:
            multi_matched_entities.append(
                {
                    "sample_id":
                        record["sample_id"],

                    "log_type":
                        record["log_type"],

                    "label":
                        entity["label"],
                }
            )

In [358]:
print(
    "BLOCK BOUNDARY VALIDATION"
)

print("=" * 60)

print(
    f"Train samples           : "
    f"{len(train_records):,}"
)

print(
    f"Cross-boundary entities : "
    f"{len(cross_boundary_entities):,}"
)

print(
    f"Multi-matched entities  : "
    f"{len(multi_matched_entities):,}"
)

BLOCK BOUNDARY VALIDATION
============================================================
Train samples           : 43,048
Cross-boundary entities : 0
Multi-matched entities  : 0

### 21.7 전체 Input 구조 분석 Summary

앞서 확인한 문자 길이, 줄 수, 임시 Block 수와 Entity 경계 검증 결과를 하나로 정리한다.

이 결과를 바탕으로 다음 단계에서 실제 Structure-aware Block Builder의 규칙을 설계한다.

특히 다음 값을 중점적으로 확인한다.

* P95 / P99 문자 길이
* 최대 줄 수
* Sample당 평균 Block 수
* 하나의 Block으로 유지되는 Sample 비율
* Block 경계를 넘는 Entity 수

In [359]:
overall_char_lengths = (
    structure_df[
        "char_length"
    ]
)

overall_line_counts = (
    structure_df[
        "line_count"
    ]
)

overall_block_counts = (
    block_analysis_df[
        "block_count"
    ]
)

In [360]:
print(
    "INPUT STRUCTURE ANALYSIS SUMMARY"
)

print("=" * 70)

print(
    f"Samples                 : "
    f"{len(train_records):,}"
)

print(
    f"Mean char length        : "
    f"{overall_char_lengths.mean():.1f}"
)

print(
    f"P95 char length         : "
    f"{np.percentile(overall_char_lengths, 95):.1f}"
)

print(
    f"P99 char length         : "
    f"{np.percentile(overall_char_lengths, 99):.1f}"
)

print(
    f"Max char length         : "
    f"{overall_char_lengths.max():,}"
)

print(
    f"Mean line count         : "
    f"{overall_line_counts.mean():.2f}"
)

print(
    f"P95 line count          : "
    f"{np.percentile(overall_line_counts, 95):.1f}"
)

print(
    f"Max line count          : "
    f"{overall_line_counts.max():,}"
)

print(
    f"Mean candidate blocks   : "
    f"{overall_block_counts.mean():.2f}"
)

print(
    f"Single-block samples    : "
    f"{block_analysis_df['single_block'].mean():.1%}"
)

print(
    f"Cross-boundary entities : "
    f"{len(cross_boundary_entities):,}"
)

INPUT STRUCTURE ANALYSIS SUMMARY
======================================================================
Samples                 : 43,048
Mean char length        : 343.2
P95 char length         : 1911.0
P99 char length         : 2285.5
Max char length         : 3,043
Mean line count         : 3.70
P95 line count          : 22.0
Max line count          : 25
Mean candidate blocks   : 1.00
Single-block samples    : 100.0%
Cross-boundary entities : 0

## 22. 구조 신호 기반 Block 규칙 설계

Input 구조 분석 결과 현재 학습 Dataset의 모든 Sample이 하나의 논리적 Block으로 유지되었고, Block 경계를 넘어가는 Entity도 발견되지 않았다.

따라서 기존 Train Dataset을 다시 세분화하지 않고 현재 Sample 단위를 유지한다.

다만 실제 서비스에서는 사용자가 여러 종류의 로그를 하나의 Text에 혼합하여 입력할 수 있으므로 별도의 Structure-aware Block Builder가 필요하다.

Block Builder는 `log_type` Metadata를 입력 조건으로 사용하지 않는다.

대신 Text 자체에서 확인할 수 있는 구조 신호를 이용하여 논리적 Block을 구성한다.

### 22.1 Block Builder 기본 원칙

Block Builder는 다음 원칙을 따른다.

1. 학습과 추론에서 동일한 Block Builder를 사용한다.
2. `log_type`은 Block 분할 조건으로 사용하지 않는다.
3. Entity가 Block 경계를 넘어가도록 분할하지 않는다.
4. Baseline 단계에서는 Stack Frame이나 기타 Text를 축약하지 않는다.
5. Block은 가능한 한 원본의 연속된 Character 구간으로 유지한다.
6. 원본 위치 복원을 위해 각 Block에 Source Segment 정보를 저장한다.
7. Token 길이에 따른 Sliding Window 처리는 Block Builder와 분리한다.
8. 한 입력에 여러 Log 구조가 섞여 있어도 처리할 수 있어야 한다.

### 22.2 구조 판정 우선순위

여러 구조 신호가 동시에 나타날 수 있으므로 다음 우선순위를 사용한다.

```text
1. PEM / Private Key Block
2. JSON Object / Array
3. Java Stack Trace / Exception Block
4. HTTP Request + Header Block
5. Timestamp 기반 Multiline Log Event
6. 일반 독립 Line
```

상위 구조 모드에 진입하면 해당 구조가 종료될 때까지 하위 규칙을 적용하지 않는다.

예를 들어 JSON 내부의 `key: value` 형태를 HTTP Header로 잘못 인식하지 않도록 한다.

### 22.3 PEM Block 규칙

다음과 같은 Private Key Marker가 발견되면 PEM Block으로 처리한다.

```text
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
```

지원 대상에는 다음과 같은 형태가 포함될 수 있다.

* PKCS8 Private Key
* RSA Private Key
* EC Private Key
* Encrypted Private Key
* OpenSSH Private Key

`BEGIN`부터 대응되는 `END`까지 하나의 Block으로 유지한다.

Baseline에서는 내부 내용을 축약하거나 제거하지 않는다.

실제 Masking Pipeline에서는 이러한 명시적 Marker를 deterministic safety rule로 활용할 수 있지만, 현재 Block Builder 단계에서는 원본 Text를 그대로 유지한다.

### 22.4 JSON Block 규칙

`{` 또는 `[`로 시작하는 구조가 발견되면 JSON 후보로 판단한다.

문자열 내부의 `{`, `}`, `[`, `]`를 제외하고 괄호 깊이를 추적하여 JSON 구조가 완전히 닫힐 때까지 하나의 Block으로 수집한다.

예:

```text
{
  "auth": {
    "type": "bearer",
    "value": "abc..."
  }
}
```

JSON을 줄 단위로 분리하지 않는 이유는 부모 Key와 형제 Field가 Entity 판단에 필요한 문맥을 제공할 수 있기 때문이다.

한 줄 JSON 역시 하나의 Object라면 하나의 Block으로 유지한다.

JSON Block이 Transformer 최대 Token 길이를 초과하는 경우의 처리는 Block Builder가 아니라 이후 Sliding Window 단계에서 수행한다.

### 22.5 Java Stack Trace Block 규칙

Java Exception Header와 이어지는 Stack Frame, `Caused by`, `Suppressed` 구조를 하나의 Exception Block으로 유지한다.

대표적인 이어짐 신호는 다음과 같다.

```text
at ...
Caused by:
Suppressed:
... N more
들여쓰기된 Stack Trace Line
```

Baseline에서는 Stack Frame을 제거하거나 축약하지 않는다.

Input 구조 분석 결과 현재 Java Stack Trace Sample은 평균 약 18줄, 최대 25줄 수준이며 모든 Entity가 하나의 Block 내부에 포함되고 있다.

실제 Token 길이를 측정한 뒤 필요할 경우에만 별도의 Long Sequence 정책을 적용한다.

### 22.6 HTTP Header Block 규칙

HTTP Request Line과 연속된 Header Line을 하나의 Block으로 유지한다.

예:

```text
GET /account HTTP/1.1
Host: example.com
Authorization: Bearer abc...
X-Request-Id: 1234
```

다음과 같은 Header 간 관계가 Entity 판단에 도움이 될 수 있으므로 Header를 한 줄씩 분리하지 않는다.

```text
Authorization: Bearer ...
X-Token-Window: 900
```

Header Block은 다음 조건 중 하나에서 종료된다.

* 빈 줄
* 새로운 독립 Log Event 시작
* 다른 명확한 구조 Block 시작
* 입력 종료

### 22.7 Timestamp 기반 Log Event 규칙

Timestamp로 시작하는 Line은 새로운 Log Event의 시작 후보로 사용한다.

예:

```text
2026-08-18 10:31:02 ERROR request failed
    user=user@example.com
    retry=2
```

첫 번째 Line 이후 들여쓰기된 Line이나 연속 메시지는 같은 Event에 포함한다.

다음 Timestamp 시작 Line이 등장하면 새로운 Block을 시작한다.

이 규칙은 주로 Application Log와 System Log에서 사용되지만, 실제 구현에서는 `log_type`을 확인하지 않고 Text 구조만 이용한다.

### 22.8 일반 Line 처리

PEM, JSON, Stack Trace, HTTP Header, Timestamp Event 중 어느 구조에도 속하지 않는 Text는 기본적으로 독립 Block으로 처리한다.

예:

```text
DB_PASSWORD=abc123
```

또는:

```text
worker completed successfully
```

다만 연속된 Configuration Key/Value 구조처럼 하나의 논리적 Section으로 판단 가능한 경우에는 다음 Block Builder 구현 단계에서 연속 Block으로 묶을 수 있도록 확장 가능하게 설계한다.

### 22.9 Block Metadata 구조

Structure-aware Block Builder가 생성하는 Block은 최소한 다음 정보를 가진다.

```text
text
source_start
source_end
segments
source_sample_id
log_type
entities
```

`log_type`은 기존 Dataset 분석을 위한 Metadata로 상속하지만 Block 생성 규칙에는 사용하지 않는다.

`segments`는 향후 Stack Frame 축약 등 비연속 원본 구간을 지원할 수 있도록 처음부터 List 형태로 저장한다.

Baseline에서는 Text를 축약하지 않으므로 모든 Block은 기본적으로 하나의 Segment만 가진다.

### 22.10 현재 Block 정책 결론

Input 구조 분석 결과를 바탕으로 다음과 같이 결정한다.

#### 기존 학습 Dataset

현재 Sample의 100%가 임시 구조 규칙에서 하나의 Block으로 유지되었다.

또한 Block 경계를 넘어가는 Entity가 0개였다.

따라서 기존 Train Dataset은 현재 Sample 단위를 그대로 하나의 Logical Block으로 사용한다.

#### 실제 추론 입력

실제 사용자가 입력하는 Text는 여러 Log Event 또는 서로 다른 구조가 혼합될 수 있으므로 Structure-aware Block Builder를 사용해 여러 Logical Block으로 분할한다.

#### Stack Trace

현재 단계에서는 Stack Frame을 제거하거나 축약하지 않는다.

Tokenizer별 실제 Token 길이를 분석한 뒤 필요할 경우에만 최적화를 검토한다.

#### 길이 제한

Character Length를 이용해 Block을 자르지 않는다.

Block Builder는 구조적 경계만 담당하고, Token 길이 초과 문제는 실제 Tokenizer를 적용한 이후 별도의 Sliding Window 단계에서 처리한다.

## 23. Structure-aware Block Builder 구현

앞선 분석에서 현재 Train Dataset의 Sample은 100% 하나의 논리적 Block으로 유지되었고, Block 경계를 넘는 Entity도 없었다.

따라서 기존 학습 Sample을 인위적으로 더 잘게 나누지 않는다.

대신 실제 추론 시 여러 종류의 로그가 하나의 Text에 섞여 들어오는 상황을 처리할 수 있도록 Structure-aware Block Builder를 구현한다.

Block Builder는 다음 원칙을 따른다.

* `log_type`을 분할 조건으로 사용하지 않는다.
* Text 자체의 구조 신호만 사용한다.
* PEM, JSON, Stack Trace, HTTP Header, Timestamp Event 등을 인식한다.
* Baseline에서는 Text를 축약하거나 제거하지 않는다.
* Block은 원본의 연속된 Character 구간을 유지한다.
* 각 Block은 원본 위치로 돌아갈 수 있도록 `segments` 정보를 가진다.
* Token 길이에 따른 Sliding Window는 이 단계에서 처리하지 않는다.

### 23.1 추가 구조 Pattern 정의

21번에서 정의한 기본 구조 Pattern에 Java Exception Header와 Stack Trace 이어짐 Line을 판별하는 Pattern을 추가한다.

Stack Trace는 Exception Header와 이어지는 `at`, `Caused by`, `Suppressed`, `... N more` Line을 하나의 Block으로 유지한다.

In [361]:
EXCEPTION_HEADER_RE = re.compile(
    r"^\s*(?:Caused by:\s*)?"
    r"[\w.$]*"
    r"(?:Exception|Error|Throwable)"
    r"\b.*$"
)


STACK_MORE_RE = re.compile(
    r"^\s*\.\.\.\s+\d+\s+more\s*$"
)

### 23.2 Line Offset 생성

Block을 생성한 뒤 원본 Character 위치를 복원하려면 각 Line이 원본 Text의 어느 위치에 존재하는지 알아야 한다.

따라서 각 Line에 다음 정보를 부여한다.

* Line Text
* 시작 Character Offset
* 종료 Character Offset

개행 문자 역시 원본 Text의 일부이므로 보존한다.

In [362]:
def build_line_spans(text):
    lines = text.splitlines(
        keepends=True
    )

    spans = []
    cursor = 0

    for index, line in enumerate(lines):
        start = cursor
        end = start + len(line)

        spans.append(
            {
                "index": index,
                "text": line,
                "start": start,
                "end": end,
            }
        )

        cursor = end

    if not lines and text:
        spans.append(
            {
                "index": 0,
                "text": text,
                "start": 0,
                "end": len(text),
            }
        )

    return spans

In [363]:
sample_text = (
    "line 1\n"
    "line 2\n"
    "line 3"
)

sample_line_spans = (
    build_line_spans(
        sample_text
    )
)


reconstructed_text = "".join(
    line["text"]
    for line in sample_line_spans
)


assert reconstructed_text == sample_text

sample_line_spans

[{'index': 0, 'text': 'line 1\n', 'start': 0, 'end': 7},
 {'index': 1, 'text': 'line 2\n', 'start': 7, 'end': 14},
 {'index': 2, 'text': 'line 3', 'start': 14, 'end': 20}]

### 23.3 JSON Block 종료 위치 탐색

JSON은 줄 수가 아니라 `{}`, `[]`의 구조를 기준으로 하나의 Block을 판단한다.

문자열 내부의 괄호는 JSON 구조의 종료로 판단하면 안 되므로 Quote와 Escape 상태를 함께 추적한다.

이 함수는 JSON 시작 위치부터 대응되는 마지막 괄호가 닫히는 Character 위치를 반환한다.

In [364]:
def find_json_end(
    text,
    start,
):
    stack = []

    in_string = False
    escaped = False

    started = False

    for index in range(
        start,
        len(text),
    ):
        char = text[index]

        if in_string:
            if escaped:
                escaped = False

            elif char == "\\":
                escaped = True

            elif char == '"':
                in_string = False

            continue

        if char == '"':
            in_string = True
            continue

        if char in "{[":
            stack.append(char)
            started = True

        elif char in "}]":
            if not stack:
                return None

            opening = stack.pop()

            valid_pair = (
                opening == "{"
                and char == "}"
            ) or (
                opening == "["
                and char == "]"
            )

            if not valid_pair:
                return None

            if (
                started
                and not stack
            ):
                return index + 1

    return None

In [365]:
json_test = """{
  "auth": {
    "type": "bearer",
    "message": "value with } inside"
  }
}"""


json_start = json_test.index("{")

json_end = find_json_end(
    json_test,
    json_start,
)


assert json_end == len(json_test)

print(
    json_test[
        json_start:json_end
    ]
)

{
  "auth": {
    "type": "bearer",
    "message": "value with } inside"
  }
}

### 23.4 구조 판별 Helper

Block Builder 내부에서 특정 Line이 어떤 구조의 시작인지 판단하기 위한 Helper 함수를 정의한다.

이 과정에서도 `log_type`은 사용하지 않는다.

In [366]:
def line_without_newline(line):
    return line.rstrip(
        "\r\n"
    )


def is_blank_line(line):
    return not line.strip()


def is_pem_begin_line(line):
    clean_line = line.strip()

    return bool(
        PEM_BEGIN_RE.match(
            clean_line
        )
    )


def is_http_request_line(line):
    return bool(
        HTTP_REQUEST_LINE_RE.match(
            line.strip()
        )
    )


def is_http_header_line(line):
    clean_line = (
        line_without_newline(
            line
        )
    )

    return bool(
        HEADER_LINE_RE.match(
            clean_line
        )
    )


def is_exception_header(line):
    return bool(
        EXCEPTION_HEADER_RE.match(
            line_without_newline(
                line
            )
        )
    )


def is_stack_continuation(line):
    clean_line = (
        line_without_newline(
            line
        )
    )

    return bool(
        STACK_FRAME_RE.match(
            clean_line
        )
        or CAUSED_BY_RE.match(
            clean_line
        )
        or STACK_MORE_RE.match(
            clean_line
        )
        or clean_line.startswith(
            (" ", "\t")
        )
    )


def is_timestamp_start(line):
    return bool(
        TIMESTAMP_RE.match(
            line_without_newline(
                line
            )
        )
    )

### 23.5 Header Block 판별

실제 입력에서는 HTTP Request Line 없이 Header만 여러 줄 연속으로 전달될 수 있다.

예:

```text
Authorization: Bearer abc.def.ghi
X-Request-Id: req-123
Content-Type: application/json
```

이 경우 각 줄을 개별 Block으로 나누면 Header 간 문맥이 끊길 수 있으므로, 연속된 Header 형태가 2줄 이상 존재하면 하나의 HTTP Header Block 후보로 판단한다.

이 단계에서는 현재 Line부터 연속해서 몇 개의 Header Line이 존재하는지만 계산한다.

실제 Block 생성과 종료 위치 결정은 이후 `build_blocks()`에서 수행한다.

In [367]:
def count_consecutive_headers(
    line_spans,
    start_index,
):
    count = 0

    for index in range(
        start_index,
        len(line_spans),
    ):
        line = line_spans[
            index
        ]["text"]

        if is_http_header_line(
            line
        ):
            count += 1

        else:
            break

    return count

### 23.6 Block 객체 생성

각 Block에는 원본 위치 정보를 함께 저장한다.

Baseline에서는 Block이 항상 원본의 연속 구간이므로 `segments`는 하나만 가진다.

향후 Stack Frame 축약처럼 비연속 원본 구간을 하나의 모델 입력으로 구성하게 되더라도 동일한 Interface를 사용할 수 있도록 처음부터 List 형태로 관리한다.

In [368]:
def create_block(
    source_text,
    start,
    end,
    structure_type,
):
    block_text = (
        source_text[
            start:end
        ]
    )

    return {
        "text": block_text,

        "source_start": start,
        "source_end": end,

        "segments": [
            {
                "block_start": 0,
                "block_end":
                    len(block_text),

                "source_start":
                    start,

                "source_end":
                    end,
            }
        ],

        "structure_type":
            structure_type,
    }

### 23.7 Structure-aware Block Builder

Block Builder는 입력 Text를 앞에서부터 순차적으로 확인한다.

우선순위는 다음과 같다.

1. PEM Private Key
2. JSON Object / Array
3. Java Stack Trace
4. HTTP Request / Header Block
5. Timestamp 기반 Log Event
6. 일반 Text

구조를 인식하면 해당 구조가 끝날 때까지 하나의 Block으로 유지한다.

Baseline에서는 어떤 Text도 삭제하거나 축약하지 않는다.

In [369]:
def extend_to_line_end(
    line_spans,
    start_index,
    end_position,
):
    """
    구조의 끝이 포함된 Line 전체를 소비한다.

    반환:
    - block_end
    - 다음에 처리할 line_index
    """

    for index in range(
        start_index,
        len(line_spans),
    ):
        line_end = (
            line_spans[index]["end"]
        )

        if end_position <= line_end:
            return (
                line_end,
                index + 1,
            )

    return (
        end_position,
        len(line_spans),
    )

In [370]:
def find_embedded_pem_end(
    text,
    search_start,
    search_end,
):
    begin_match = PEM_BEGIN_RE.search(
        text,
        search_start,
        search_end,
    )

    if begin_match is None:
        return None

    begin_marker = begin_match.group(0)

    end_marker = begin_marker.replace(
        "BEGIN",
        "END",
        1,
    )

    end_start = text.find(
        end_marker,
        begin_match.end(),
    )

    # BEGIN은 존재하지만 END를 찾지 못한 경우
    # Entity 중간에서 Block을 자르지 않기 위해
    # 입력 끝까지 포함한다.
    if end_start < 0:
        return len(text)

    return (
        end_start
        + len(end_marker)
    )

In [371]:
def build_blocks(
    text,
    safety_max_chars=None,
):
    if not text:
        return []

    if (
        safety_max_chars is not None
        and len(text) > safety_max_chars
    ):
        raise ValueError(
            "Input exceeds safety_max_chars: "
            f"{len(text):,} > "
            f"{safety_max_chars:,}"
        )

    line_spans = (
        build_line_spans(
            text
        )
    )

    blocks = []

    line_index = 0

    # 비정상적인 무한 반복을
    # 방지하기 위한 안전장치
    iteration_count = 0

    max_iterations = (
        len(line_spans) * 3
        + 10
    )


    while line_index < len(
        line_spans
    ):
        iteration_count += 1

        if (
            iteration_count
            > max_iterations
        ):
            raise RuntimeError(
                "Block Builder did not make "
                "forward progress. "
                f"line_index={line_index}, "
                f"lines={len(line_spans)}"
            )

        current = (
            line_spans[
                line_index
            ]
        )

        line = current["text"]

        start = current["start"]


        # ---------------------------------
        # 1. PEM Private Key
        # ---------------------------------
        if is_pem_begin_line(
            line
        ):
            begin_match = (
                PEM_BEGIN_RE.search(
                    line
                )
            )

            begin_marker = (
                begin_match.group(0)
            )

            end_marker = (
                begin_marker.replace(
                    "BEGIN",
                    "END",
                    1,
                )
            )

            raw_end_position = (
                text.find(
                    end_marker,
                    start
                    + len(begin_marker),
                )
            )

            if raw_end_position >= 0:
                raw_end_position += (
                    len(end_marker)
                )

                (
                    end_position,
                    next_line_index,
                ) = extend_to_line_end(
                    line_spans,
                    line_index,
                    raw_end_position,
                )

            else:
                end_position = len(
                    text
                )

                next_line_index = len(
                    line_spans
                )

            blocks.append(
                create_block(
                    text,
                    start,
                    end_position,
                    "PEM",
                )
            )

            line_index = (
                next_line_index
            )

            continue


        # ---------------------------------
        # 2. JSON
        # ---------------------------------
        stripped_line = (
            line.lstrip()
        )

        leading_space = (
            len(line)
            - len(stripped_line)
        )

        json_start = (
            start
            + leading_space
        )

        if (
            stripped_line.startswith(
                "{"
            )
            or stripped_line.startswith(
                "["
            )
        ):
            raw_json_end = (
                find_json_end(
                    text,
                    json_start,
                )
            )

            if raw_json_end is not None:
                (
                    end_position,
                    next_line_index,
                ) = extend_to_line_end(
                    line_spans,
                    line_index,
                    raw_json_end,
                )

                blocks.append(
                    create_block(
                        text,
                        start,
                        end_position,
                        "JSON",
                    )
                )

                line_index = (
                    next_line_index
                )

                continue


        # ---------------------------------
        # 3. Java Stack Trace
        # ---------------------------------
        if is_exception_header(
            line
        ):
            end_index = (
                line_index + 1
            )

            # Exception Header 내부에서
            # Multiline PEM이 시작되는지 확인
            embedded_pem_end = (
                find_embedded_pem_end(
                    text,
                    start,
                    current["end"],
                )
            )

            # PEM이 포함된 경우
            # END Marker가 포함된 Line까지
            # 먼저 하나의 Stack Trace로 소비
            if embedded_pem_end is not None:
                (
                    _,
                    end_index,
                ) = extend_to_line_end(
                    line_spans,
                    line_index,
                    embedded_pem_end,
                )

            # PEM 이후에도 이어지는
            # Stack Frame / Caused by /
            # 추가 Exception Header 등을 수집
            while (
                end_index
                < len(line_spans)
            ):
                next_line = (
                    line_spans[
                        end_index
                    ]["text"]
                )

                if (
                    is_stack_continuation(
                        next_line
                    )
                    or is_exception_header(
                        next_line
                    )
                ):
                    end_index += 1
                    continue

                break

            end_position = (
                line_spans[
                    end_index - 1
                ]["end"]
            )

            blocks.append(
                create_block(
                    text,
                    start,
                    end_position,
                    "JAVA_STACK_TRACE",
                )
            )

            line_index = (
                end_index
            )

            continue


        # ---------------------------------
        # 4. HTTP Request + Headers
        # ---------------------------------
        if is_http_request_line(
            line
        ):
            end_index = (
                line_index + 1
            )

            while (
                end_index
                < len(line_spans)
            ):
                next_line = (
                    line_spans[
                        end_index
                    ]["text"]
                )

                if is_http_header_line(
                    next_line
                ):
                    end_index += 1
                    continue

                if is_blank_line(
                    next_line
                ):
                    end_index += 1

                break

            end_position = (
                line_spans[
                    end_index - 1
                ]["end"]
            )

            blocks.append(
                create_block(
                    text,
                    start,
                    end_position,
                    "HTTP_HEADER",
                )
            )

            line_index = (
                end_index
            )

            continue


        # ---------------------------------
        # 4-2. Header-only Block
        # ---------------------------------
        consecutive_headers = (
            count_consecutive_headers(
                line_spans,
                line_index,
            )
        )

        if consecutive_headers >= 2:
            end_index = (
                line_index
                + consecutive_headers
            )

            if (
                end_index
                < len(line_spans)
                and is_blank_line(
                    line_spans[
                        end_index
                    ]["text"]
                )
            ):
                end_index += 1

            end_position = (
                line_spans[
                    end_index - 1
                ]["end"]
            )

            blocks.append(
                create_block(
                    text,
                    start,
                    end_position,
                    "HTTP_HEADER",
                )
            )

            line_index = (
                end_index
            )

            continue


        # ---------------------------------
        # 5. Timestamp Event
        # ---------------------------------
        if is_timestamp_start(
            line
        ):
            end_index = (
                line_index + 1
            )

            while (
                end_index
                < len(line_spans)
            ):
                next_line = (
                    line_spans[
                        end_index
                    ]["text"]
                )

                if is_timestamp_start(
                    next_line
                ):
                    break

                if (
                    is_pem_begin_line(
                        next_line
                    )
                    or is_http_request_line(
                        next_line
                    )
                    or is_exception_header(
                        next_line
                    )
                ):
                    break

                next_stripped = (
                    next_line.lstrip()
                )

                if (
                    next_stripped.startswith(
                        "{"
                    )
                    or next_stripped.startswith(
                        "["
                    )
                ):
                    break

                end_index += 1

            end_position = (
                line_spans[
                    end_index - 1
                ]["end"]
            )

            blocks.append(
                create_block(
                    text,
                    start,
                    end_position,
                    "TIMESTAMP_EVENT",
                )
            )

            line_index = (
                end_index
            )

            continue


        # ---------------------------------
        # 6. General Text
        # ---------------------------------
        end_index = (
            line_index + 1
        )

        while (
            end_index
            < len(line_spans)
        ):
            next_line = (
                line_spans[
                    end_index
                ]["text"]
            )

            next_stripped = (
                next_line.lstrip()
            )

            strong_structure_start = (
                is_pem_begin_line(
                    next_line
                )
                or is_http_request_line(
                    next_line
                )
                or is_exception_header(
                    next_line
                )
                or is_timestamp_start(
                    next_line
                )
                or next_stripped.startswith(
                    "{"
                )
                or next_stripped.startswith(
                    "["
                )
            )

            if strong_structure_start:
                break

            header_count = (
                count_consecutive_headers(
                    line_spans,
                    end_index,
                )
            )

            if header_count >= 2:
                break

            end_index += 1

        end_position = (
            line_spans[
                end_index - 1
            ]["end"]
        )

        blocks.append(
            create_block(
                text,
                start,
                end_position,
                "GENERAL",
            )
        )

        line_index = (
            end_index
        )


    return blocks

### 23.8 Mixed Input 동작 확인

Application Log, HTTP Header, JSON, Java Stack Trace가 하나의 Text에 섞여 있는 입력을 만들어 Block Builder가 `log_type` 없이 구조를 분리할 수 있는지 확인한다.

In [372]:
mixed_input = """2026-08-18 10:31:02 ERROR request failed user=member42
2026-08-18 10:31:03 INFO retry scheduled

GET /account HTTP/1.1
Host: example.test
Authorization: Bearer abc.def.ghi
X-Request-Id: req-123

{
  "email": "user@example.com",
  "status": "failed"
}

com.example.AuthException: authentication failed
    at com.example.AuthService.login(AuthService.java:81)
    at com.example.Controller.login(Controller.java:44)
Caused by: java.lang.IllegalStateException: invalid state
    at com.example.Session.load(Session.java:31)
"""


mixed_blocks = (
    build_blocks(
        mixed_input
    )
)


print(
    f"Mixed blocks : "
    f"{len(mixed_blocks)}"
)


for index, block in enumerate(
    mixed_blocks,
    start=1,
):
    print(
        "\n"
        + "=" * 60
    )

    print(
        f"Block {index}"
    )

    print(
        f"Type   : "
        f"{block['structure_type']}"
    )

    print(
        f"Source : "
        f"{block['source_start']} "
        f"~ "
        f"{block['source_end']}"
    )

    print("-" * 60)

    print(
        block["text"]
    )

Mixed blocks : 6

============================================================
Block 1
Type   : TIMESTAMP_EVENT
Source : 0 ~ 55
------------------------------------------------------------
2026-08-18 10:31:02 ERROR request failed user=member42


============================================================
Block 2
Type   : TIMESTAMP_EVENT
Source : 55 ~ 97
------------------------------------------------------------
2026-08-18 10:31:03 INFO retry scheduled



============================================================
Block 3
Type   : HTTP_HEADER
Source : 97 ~ 195
------------------------------------------------------------
GET /account HTTP/1.1
Host: example.test
Authorization: Bearer abc.def.ghi
X-Request-Id: req-123



============================================================
Block 4
Type   : JSON
Source : 195 ~ 251
------------------------------------------------------------
{
  "email": "user@example.com",
  "status": "failed"
}


============================================================
Block 5
Type   : GENERAL
Source : 251 ~ 252
------------------------------------------------------------



============================================================
Block 6
Type   : JAVA_STACK_TRACE
Source : 252 ~ 522
------------------------------------------------------------
com.example.AuthException: authentication failed
    at com.example.AuthService.login(AuthService.java:81)
    at com.example.Controller.login(Controller.java:44)
Caused by: java.lang.IllegalStateException: invalid state
    at com.example.Session.load(Session.java:31)

### 23.9 원본 Text 보존 검증

Block Builder는 Text를 삭제하거나 수정하지 않는다.

따라서 생성된 모든 Block의 Text를 순서대로 다시 합쳤을 때 원본 입력과 완전히 동일해야 한다.

In [373]:
mixed_reconstructed = "".join(
    block["text"]
    for block in mixed_blocks
)


print(
    f"Original length      : "
    f"{len(mixed_input):,}"
)

print(
    f"Reconstructed length : "
    f"{len(mixed_reconstructed):,}"
)

print(
    f"Exact reconstruction : "
    f"{mixed_input == mixed_reconstructed}"
)


assert (
    mixed_input
    == mixed_reconstructed
)

Original length      : 522
Reconstructed length : 522
Exact reconstruction : True

In [374]:
segment_mapping_errors = 0


for block in mixed_blocks:
    for segment in block[
        "segments"
    ]:
        block_piece = (
            block["text"][
                segment[
                    "block_start"
                ]:
                segment[
                    "block_end"
                ]
            ]
        )

        source_piece = (
            mixed_input[
                segment[
                    "source_start"
                ]:
                segment[
                    "source_end"
                ]
            ]
        )

        if (
            block_piece
            != source_piece
        ):
            segment_mapping_errors += 1


print(
    f"Segment mapping errors : "
    f"{segment_mapping_errors}"
)


assert segment_mapping_errors == 0

Segment mapping errors : 0

### 23.10.1 Block Builder Smoke Test

전체 Train Dataset에 적용하기 전에 일부 Sample에 Block Builder를 적용하여 무한 반복이나 원본 복원 오류가 없는지 확인한다.

특히 PEM, JSON 등 여러 줄 또는 구조화된 입력이 포함된 Sample에서도 정상적으로 다음 Block으로 진행되는지 확인한다.

In [375]:
SMOKE_TEST_SIZE = 1000


smoke_errors = []

smoke_block_counts = []


for index, record in enumerate(
    train_records[
        :SMOKE_TEST_SIZE
    ]
):
    text = record["text"]

    try:
        blocks = build_blocks(
            text
        )

        reconstructed = "".join(
            block["text"]
            for block in blocks
        )

        smoke_block_counts.append(
            len(blocks)
        )

        if reconstructed != text:
            smoke_errors.append(
                {
                    "sample_id":
                        record["sample_id"],

                    "reason":
                        "reconstruction_error",
                }
            )

    except Exception as error:
        smoke_errors.append(
            {
                "sample_id":
                    record["sample_id"],

                "reason":
                    repr(error),
            }
        )


print(
    "BLOCK BUILDER SMOKE TEST"
)

print("=" * 60)

print(
    f"Samples tested       : "
    f"{SMOKE_TEST_SIZE:,}"
)

print(
    f"Errors               : "
    f"{len(smoke_errors):,}"
)

print(
    f"Total blocks         : "
    f"{sum(smoke_block_counts):,}"
)

print(
    f"Max blocks / sample  : "
    f"{max(smoke_block_counts):,}"
)

BLOCK BUILDER SMOKE TEST
============================================================
Samples tested       : 1,000
Errors               : 0
Total blocks         : 1,000
Max blocks / sample  : 1

In [376]:
pem_regression_text = (
    'PRIVATE_KEY="'
    '-----BEGIN PRIVATE KEY-----'
    'abc123'
    '-----END PRIVATE KEY-----'
    '"\n'
    'PORT=8080'
)


pem_blocks = build_blocks(
    pem_regression_text
)


pem_reconstructed = "".join(
    block["text"]
    for block in pem_blocks
)


print(
    f"Blocks               : "
    f"{len(pem_blocks)}"
)

print(
    f"Exact reconstruction : "
    f"{pem_reconstructed == pem_regression_text}"
)


assert (
    pem_reconstructed
    == pem_regression_text
)

Blocks               : 1
Exact reconstruction : True

### 23.11 Train Dataset 전체 적용

Smoke Test와 PEM Regression Test에서 Block Builder가 정상적으로 동작하는 것을 확인했다.

이제 최종 Train Dataset 43,048개 전체에 Block Builder를 적용하여 다음 항목을 검증한다.

* 생성된 전체 Block 수
* 하나의 Block으로 유지되는 Sample 비율
* Sample당 최대 Block 수
* 원본 Text 복원 오류
* Segment Mapping 오류
* Block Builder 실행 오류

대규모 검증 과정에서 불필요한 메모리 사용을 줄이기 위해 모든 결과를 저장하지 않고 통계 값만 누적한다.

In [377]:
from collections import Counter


train_block_counter = Counter()

total_blocks = 0

reconstruction_error_count = 0
segment_mapping_error_count = 0
builder_error_count = 0

error_examples = []

MAX_ERROR_EXAMPLES = 10

In [378]:
for index, record in enumerate(
    train_records,
    start=1,
):
    text = record["text"]

    try:
        blocks = build_blocks(
            text
        )

    except Exception as error:
        builder_error_count += 1

        if (
            len(error_examples)
            < MAX_ERROR_EXAMPLES
        ):
            error_examples.append(
                {
                    "sample_id":
                        record["sample_id"],

                    "error":
                        repr(error),
                }
            )

        continue


    block_count = len(
        blocks
    )

    train_block_counter[
        block_count
    ] += 1

    total_blocks += (
        block_count
    )


    reconstructed = "".join(
        block["text"]
        for block in blocks
    )

    if reconstructed != text:
        reconstruction_error_count += 1

        if (
            len(error_examples)
            < MAX_ERROR_EXAMPLES
        ):
            error_examples.append(
                {
                    "sample_id":
                        record["sample_id"],

                    "error":
                        "reconstruction_error",
                }
            )


    for block in blocks:
        for segment in block[
            "segments"
        ]:
            block_piece = (
                block["text"][
                    segment[
                        "block_start"
                    ]:
                    segment[
                        "block_end"
                    ]
                ]
            )

            source_piece = (
                text[
                    segment[
                        "source_start"
                    ]:
                    segment[
                        "source_end"
                    ]
                ]
            )

            if block_piece != source_piece:
                segment_mapping_error_count += 1

                if (
                    len(error_examples)
                    < MAX_ERROR_EXAMPLES
                ):
                    error_examples.append(
                        {
                            "sample_id":
                                record[
                                    "sample_id"
                                ],

                            "error":
                                "segment_mapping_error",
                        }
                    )


    if index % 5000 == 0:
        print(
            f"Processed "
            f"{index:,} / "
            f"{len(train_records):,}"
        )

Processed 5,000 / 43,048
Processed 10,000 / 43,048
Processed 15,000 / 43,048
Processed 20,000 / 43,048
Processed 25,000 / 43,048
Processed 30,000 / 43,048
Processed 35,000 / 43,048
Processed 40,000 / 43,048

In [379]:
single_block_samples = (
    train_block_counter[1]
)


valid_samples = (
    len(train_records)
    - builder_error_count
)


single_block_ratio = (
    single_block_samples
    / valid_samples
    if valid_samples
    else 0
)


max_blocks_per_sample = (
    max(
        train_block_counter.keys()
    )
    if train_block_counter
    else 0
)


print(
    "STRUCTURE-AWARE BLOCK BUILDER SUMMARY"
)

print("=" * 65)

print(
    f"Train samples            : "
    f"{len(train_records):,}"
)

print(
    f"Generated blocks         : "
    f"{total_blocks:,}"
)

print(
    f"Single-block samples     : "
    f"{single_block_samples:,}"
)

print(
    f"Single-block ratio       : "
    f"{single_block_ratio:.1%}"
)

print(
    f"Max blocks per sample    : "
    f"{max_blocks_per_sample:,}"
)

print(
    f"Builder errors           : "
    f"{builder_error_count:,}"
)

print(
    f"Reconstruction errors    : "
    f"{reconstruction_error_count:,}"
)

print(
    f"Segment mapping errors   : "
    f"{segment_mapping_error_count:,}"
)

STRUCTURE-AWARE BLOCK BUILDER SUMMARY
=================================================================
Train samples            : 43,048
Generated blocks         : 44,626
Single-block samples     : 41,470
Single-block ratio       : 96.3%
Max blocks per sample    : 2
Builder errors           : 0
Reconstruction errors    : 0
Segment mapping errors   : 0

### 23.12 Multi-block Sample 분석

Structure-aware Block Builder를 전체 Train Dataset에 적용한 결과 87.8%의 Sample은 하나의 Block으로 유지되었지만, 일부 Sample은 두 개의 Block으로 분리되었다.

현재 분할 자체가 오류라고 볼 수는 없다.

실제 Builder는 21번의 임시 분석 규칙보다 세밀하게 JSON, PEM, HTTP Header, Timestamp 등의 구조 경계를 판별하기 때문이다.

따라서 Block-local Label Remapping을 수행하기 전에 다음을 확인한다.

- 어떤 Log Type에서 Multi-block Sample이 발생하는지
- 어떤 구조 조합으로 분리되는지
- Entity가 Block 경계를 넘어가는 경우가 존재하는지

In [380]:
multi_block_by_log_type = Counter()

structure_combinations = Counter()

multi_block_examples = []

MAX_MULTI_BLOCK_EXAMPLES = 10


for record in train_records:
    blocks = build_blocks(
        record["text"]
    )

    if len(blocks) > 1:
        multi_block_by_log_type[
            record["log_type"]
        ] += 1

        structure_types = tuple(
            block["structure_type"]
            for block in blocks
        )

        structure_combinations[
            structure_types
        ] += 1

        if (
            len(multi_block_examples)
            < MAX_MULTI_BLOCK_EXAMPLES
        ):
            multi_block_examples.append(
                {
                    "sample_id":
                        record["sample_id"],

                    "log_type":
                        record["log_type"],

                    "structure_types":
                        structure_types,

                    "text":
                        record["text"],
                }
            )

In [381]:
print(
    "MULTI-BLOCK SAMPLES BY LOG TYPE"
)

print("=" * 60)


for log_type, count in (
    multi_block_by_log_type
    .most_common()
):
    print(
        f"{log_type:<25} "
        f"{count:>6,}"
    )

MULTI-BLOCK SAMPLES BY LOG TYPE
============================================================
JAVA_STACK_TRACE           1,578

In [382]:
print(
    "BLOCK STRUCTURE COMBINATIONS"
)

print("=" * 60)


for structures, count in (
    structure_combinations
    .most_common()
):
    print(
        f"{str(structures):<50} "
        f"{count:>6,}"
    )

BLOCK STRUCTURE COMBINATIONS
============================================================
('JAVA_STACK_TRACE', 'GENERAL')                     1,578

### 23.13 Entity Block Boundary 검증

실제 Structure-aware Block Builder가 Sample을 여러 Block으로 분리하더라도 하나의 Entity 전체가 반드시 하나의 Block 안에 포함되어야 한다.

Entity가 두 Block 사이에서 잘리는 경우 해당 Block 규칙은 학습 Dataset에 사용할 수 없다.

따라서 모든 Train Entity를 대상으로 실제 Builder의 Block 경계를 검증한다.

목표는 다음과 같다.

`Cross-boundary Entity = 0`

In [383]:
cross_boundary_entities = []

multi_matched_entities = []

total_entities = 0


for record in train_records:
    blocks = build_blocks(
        record["text"]
    )

    block_spans = [
        (
            block["source_start"],
            block["source_end"],
        )
        for block in blocks
    ]

    for entity in record[
        "entities"
    ]:
        total_entities += 1

        matching_blocks = []

        for block_index, (
            block_start,
            block_end,
        ) in enumerate(
            block_spans
        ):
            if (
                entity["start"]
                >= block_start
                and entity["end"]
                <= block_end
            ):
                matching_blocks.append(
                    block_index
                )

        if len(matching_blocks) == 0:
            cross_boundary_entities.append(
                {
                    "sample_id":
                        record["sample_id"],

                    "log_type":
                        record["log_type"],

                    "label":
                        entity["label"],

                    "value":
                        entity["value"],

                    "start":
                        entity["start"],

                    "end":
                        entity["end"],

                    "block_spans":
                        block_spans,
                }
            )

        elif len(matching_blocks) > 1:
            multi_matched_entities.append(
                {
                    "sample_id":
                        record["sample_id"],

                    "label":
                        entity["label"],
                }
            )

In [384]:
print(
    "ENTITY BLOCK BOUNDARY VALIDATION"
)

print("=" * 65)

print(
    f"Total entities          : "
    f"{total_entities:,}"
)

print(
    f"Cross-boundary entities : "
    f"{len(cross_boundary_entities):,}"
)

print(
    f"Multi-matched entities  : "
    f"{len(multi_matched_entities):,}"
)

ENTITY BLOCK BOUNDARY VALIDATION
=================================================================
Total entities          : 55,398
Cross-boundary entities : 0
Multi-matched entities  : 0

### 23.14 Multi-block 분할 경계 확인

Entity Block Boundary 검증 결과 Entity가 Block 사이에서 잘리는 문제는 발견되지 않았다.

하지만 Java Stack Trace Sample의 대부분이 두 개의 Block으로 분리되고 있으므로, 해당 분할이 실제 논리적 구조에 적합한지 확인한다.

전체 Text를 출력하지 않고 각 Block의 시작과 끝 부분만 확인하여 어떤 Line을 기준으로 Block이 분리되는지 분석한다.

In [385]:
TARGET_COMBINATIONS = [
    (
        "JAVA_STACK_TRACE",
        "JAVA_STACK_TRACE",
    ),
    (
        "JAVA_STACK_TRACE",
        "GENERAL",
    ),
    (
        "PEM",
        "JAVA_STACK_TRACE",
    ),
]


examples_by_combination = {
    combination: []
    for combination in TARGET_COMBINATIONS
}


for record in train_records:
    blocks = build_blocks(
        record["text"]
    )

    structures = tuple(
        block["structure_type"]
        for block in blocks
    )

    if (
        structures
        in examples_by_combination
        and len(
            examples_by_combination[
                structures
            ]
        ) < 2
    ):
        examples_by_combination[
            structures
        ].append(
            {
                "sample_id":
                    record["sample_id"],

                "blocks":
                    blocks,
            }
        )

    if all(
        len(examples) >= 2
        for examples
        in examples_by_combination.values()
    ):
        break

In [386]:
def summarize_block_text(
    text,
    edge_lines=2,
):
    lines = text.splitlines()

    if len(lines) <= (
        edge_lines * 2
    ):
        return lines

    return (
        lines[:edge_lines]
        + ["..."]
        + lines[-edge_lines:]
    )

In [387]:
for combination, examples in (
    examples_by_combination.items()
):
    print(
        "\n"
        + "=" * 80
    )

    print(
        "COMBINATION:",
        combination,
    )

    print("=" * 80)

    for example in examples:
        print(
            "\nSample:",
            example["sample_id"],
        )

        for index, block in enumerate(
            example["blocks"],
            start=1,
        ):
            print(
                f"\n--- Block {index} "
                f"[{block['structure_type']}] "
                f"{block['source_start']}:"
                f"{block['source_end']} ---"
            )

            for line in summarize_block_text(
                block["text"]
            ):
                print(
                    repr(line)
                )

================================================================================
COMBINATION: ('JAVA_STACK_TRACE', 'JAVA_STACK_TRACE')
================================================================================

================================================================================
COMBINATION: ('JAVA_STACK_TRACE', 'GENERAL')
================================================================================

Sample: java_stack_trace_00001

--- Block 1 [JAVA_STACK_TRACE] 0:88 ---
'java.lang.IllegalArgumentException: Invalid request parameter userId=value_dx06PyUa4dLF'

--- Block 2 [GENERAL] 88:524 ---
'FreezeWarning below JavaSourceViewer.modelStyleRange2WidgetStyleRange (thrown in ProjectionMapping.findFragmentIndex)'
'    at org.eclipse.ui.internal.monitoring.DefaultUiFreezeEventLogger.log(DefaultUiFreezeEventLogger.java:104)'
'    at org.eclipse.ui.internal.monitoring.EventLoopMonitorThread.logEvent(EventLoopMonitorThread.java:785)'
'    at org.eclipse.ui.internal.monitoring.EventLoopMonitorThread.run(EventLoopMonitorThread.java:638)'

Sample: java_stack_trace_00007

--- Block 1 [JAVA_STACK_TRACE] 0:79 ---
'java.lang.RuntimeException: Request from client 2001:db8:9388:f632::666 failed'

--- Block 2 [GENERAL] 79:1740 ---
'3rd party caused ClassNotFoundException below Compiler.resolve'
'    at Snm6T1OkzT81P+xx.lSy8AzyCH/ZWvnrA(I94GDC4A7zILR+Mx:-1)'
'...'
'    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:126)'
'    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.access$0(JavaReconcilingStrategy.java:108)'

================================================================================
COMBINATION: ('PEM', 'JAVA_STACK_TRACE')
================================================================================

In [388]:
for record in train_records:
    if (
        record["log_type"]
        != "ENV_CONFIG"
    ):
        continue

    blocks = build_blocks(
        record["text"]
    )

    structures = tuple(
        block["structure_type"]
        for block in blocks
    )

    if structures == (
        "GENERAL",
        "PEM",
    ):
        print(
            "ENV_CONFIG EXAMPLE"
        )

        print("=" * 70)

        for index, block in enumerate(
            blocks,
            start=1,
        ):
            print(
                f"\nBlock {index} "
                f"[{block['structure_type']}]"
            )

            print(
                block["text"]
            )

        break

### 23.14 Multi-block 분석 결과 및 Block 규칙 수정

Multi-block Sample을 확인한 결과 두 가지 과도한 분할 문제가 발견되었다.

#### Java Stack Trace

일부 Java Stack Trace Sample은 최상위 Exception Header 다음에 또 다른 Exception Header가 이어진다.

예:

    java.lang.RuntimeException: request failed
    SocketTimeoutException below ...
        at ...
        at ...

기존 Block Builder는 두 번째 Exception Header를 새로운 Block의 시작으로 판단하여 하나의 Stack Trace를 두 Block으로 분리했다.

따라서 Stack Trace를 수집하는 동안 새로운 Exception Header가 이어지는 경우에도 동일한 Stack Trace Block에 포함하도록 수정한다.

#### Embedded PEM

ENV_CONFIG와 Exception Message 안에 PEM 문자열이 값으로 포함될 수 있다.

예:

    crypto:
      private-key: "-----BEGIN PRIVATE KEY-----...-----END PRIVATE KEY-----"

이 경우 PEM은 독립적인 입력 구조가 아니라 상위 Configuration 또는 Log Event의 일부이다.

따라서 PEM Marker가 Line 자체의 구조로 시작하는 경우에만 독립적인 PEM Block으로 판단한다.

다른 Log 또는 Configuration 값 안에 포함된 PEM 문자열은 해당 Logical Block의 문맥을 유지한다.

### 23.15 Block 규칙 수정 Regression Test

수정한 Block 규칙이 실제로 Java Stack Trace와 Embedded PEM의 과도한 분할 문제를 해결했는지 확인한다.

다음 두 경우를 검증한다.

- 연속된 Exception Header가 하나의 Stack Trace Block으로 유지되는지
- YAML Configuration 내부의 PEM Value가 부모 Configuration과 같은 Block으로 유지되는지

In [389]:
stack_regression_text = """java.lang.RuntimeException: Request failed
SocketTimeoutException below ExecutorClientWrapper.execute
    at org.example.Client.execute(Client.java:100)
    at org.example.Service.run(Service.java:50)
"""


stack_regression_blocks = build_blocks(
    stack_regression_text
)


print(
    "JAVA STACK TRACE"
)

print("=" * 50)

print(
    f"Blocks : "
    f"{len(stack_regression_blocks)}"
)

print(
    "Types  :",
    [
        block["structure_type"]
        for block
        in stack_regression_blocks
    ],
)

print(
    "Exact reconstruction :",
    "".join(
        block["text"]
        for block
        in stack_regression_blocks
    )
    == stack_regression_text,
)

JAVA STACK TRACE
==================================================
Blocks : 1
Types  : ['JAVA_STACK_TRACE']
Exact reconstruction : True

In [390]:
env_regression_text = """crypto:
  private-key: "-----BEGIN PRIVATE KEY-----abc123-----END PRIVATE KEY-----"
"""


env_regression_blocks = build_blocks(
    env_regression_text
)


print(
    "ENV CONFIG"
)

print("=" * 50)

print(
    f"Blocks : "
    f"{len(env_regression_blocks)}"
)

print(
    "Types  :",
    [
        block["structure_type"]
        for block
        in env_regression_blocks
    ],
)

print(
    "Exact reconstruction :",
    "".join(
        block["text"]
        for block
        in env_regression_blocks
    )
    == env_regression_text,
)

ENV CONFIG
==================================================
Blocks : 1
Types  : ['GENERAL']
Exact reconstruction : True

### 23.16 Cross-boundary Entity 원인 분석

수정된 Structure-aware Block Builder를 Train Dataset 전체에 적용한 결과 원본 Text와 Segment Mapping은 정상적으로 보존되었지만, 229개의 Entity가 Block 경계를 넘어가는 문제가 발견되었다.

Block-local Label Remapping을 수행하려면 모든 Entity가 정확히 하나의 Block 내부에 완전히 포함되어야 한다.

따라서 다음 항목을 분석한다.

- 어떤 Entity Label에서 문제가 발생하는지
- 어떤 Log Type에서 문제가 발생하는지
- 어떤 Block 구조 사이에서 Entity가 잘리는지
- 실제 Entity 주변 Text와 Block 경계

분석 결과를 바탕으로 Block Builder의 경계 규칙을 수정한다.

In [391]:
cross_boundary_by_label = Counter(
    item["label"]
    for item in cross_boundary_entities
)

cross_boundary_by_log_type = Counter(
    item["log_type"]
    for item in cross_boundary_entities
)


print(
    "CROSS-BOUNDARY BY ENTITY LABEL"
)

print("=" * 60)

for label, count in (
    cross_boundary_by_label
    .most_common()
):
    print(
        f"{label:<25} "
        f"{count:>6,}"
    )


print(
    "\nCROSS-BOUNDARY BY LOG TYPE"
)

print("=" * 60)

for log_type, count in (
    cross_boundary_by_log_type
    .most_common()
):
    print(
        f"{log_type:<25} "
        f"{count:>6,}"
    )

CROSS-BOUNDARY BY ENTITY LABEL
============================================================

CROSS-BOUNDARY BY LOG TYPE
============================================================

In [392]:
boundary_combinations = Counter()

boundary_examples = []

MAX_BOUNDARY_EXAMPLES = 12


for record in train_records:
    blocks = build_blocks(
        record["text"]
    )

    if len(blocks) <= 1:
        continue

    for entity in record["entities"]:
        entity_start = entity["start"]
        entity_end = entity["end"]

        matching_blocks = [
            index
            for index, block in enumerate(blocks)
            if (
                entity_start
                >= block["source_start"]
                and entity_end
                <= block["source_end"]
            )
        ]

        if matching_blocks:
            continue

        crossed_boundary = None

        for index in range(
            len(blocks) - 1
        ):
            boundary = (
                blocks[index][
                    "source_end"
                ]
            )

            if (
                entity_start
                < boundary
                < entity_end
            ):
                crossed_boundary = (
                    index
                )
                break

        if crossed_boundary is None:
            continue

        left_block = blocks[
            crossed_boundary
        ]

        right_block = blocks[
            crossed_boundary + 1
        ]

        combination = (
            left_block[
                "structure_type"
            ],
            right_block[
                "structure_type"
            ],
            entity["label"],
        )

        boundary_combinations[
            combination
        ] += 1

        if (
            len(boundary_examples)
            < MAX_BOUNDARY_EXAMPLES
        ):
            boundary_examples.append(
                {
                    "sample_id":
                        record["sample_id"],

                    "log_type":
                        record["log_type"],

                    "label":
                        entity["label"],

                    "value":
                        entity["value"],

                    "entity_start":
                        entity_start,

                    "entity_end":
                        entity_end,

                    "boundary":
                        left_block[
                            "source_end"
                        ],

                    "left_type":
                        left_block[
                            "structure_type"
                        ],

                    "right_type":
                        right_block[
                            "structure_type"
                        ],

                    "text":
                        record["text"],
                }
            )

In [393]:
print(
    "CROSS-BOUNDARY STRUCTURE COMBINATIONS"
)

print("=" * 80)

for combination, count in (
    boundary_combinations
    .most_common()
):
    print(
        f"{str(combination):<65} "
        f"{count:>6,}"
    )

CROSS-BOUNDARY STRUCTURE COMBINATIONS
================================================================================

In [394]:
CONTEXT_SIZE = 100


for example in boundary_examples:
    text = example["text"]

    entity_start = (
        example[
            "entity_start"
        ]
    )

    entity_end = (
        example[
            "entity_end"
        ]
    )

    boundary = (
        example[
            "boundary"
        ]
    )

    context_start = max(
        0,
        min(
            entity_start,
            boundary,
        )
        - CONTEXT_SIZE,
    )

    context_end = min(
        len(text),
        max(
            entity_end,
            boundary,
        )
        + CONTEXT_SIZE,
    )

    context = text[
        context_start:
        context_end
    ]

    print(
        "\n"
        + "=" * 80
    )

    print(
        "Sample:",
        example["sample_id"],
    )

    print(
        "Log Type:",
        example["log_type"],
    )

    print(
        "Entity:",
        example["label"],
    )

    print(
        "Blocks:",
        example["left_type"],
        "→",
        example["right_type"],
    )

    print(
        "Entity span:",
        (
            entity_start,
            entity_end,
        ),
    )

    print(
        "Boundary:",
        boundary,
    )

    print(
        "Value:",
        repr(
            example["value"]
        ),
    )

    print(
        "Context:",
        repr(context),
    )

### 23.19 Embedded PEM이 포함된 Stack Trace 처리

Cross-boundary Entity를 분석한 결과 229건 모두 Java Stack Trace의 Exception Message 내부에 포함된 Multiline Private Key에서 발생했다.

예외 메시지의 첫 번째 Line에 `-----BEGIN PRIVATE KEY-----`가 포함되어 있지만, 이후 Base64 본문 Line은 일반적인 Stack Trace continuation Pattern과 일치하지 않아 기존 Block Builder가 Private Key 중간에서 Block을 종료했다.

Private Key는 `BEGIN`과 `END` Marker가 명확하게 정의되어 있으므로, Java Stack Trace의 Exception Header 내부에서 PEM 시작 Marker가 발견되면 대응되는 종료 Marker까지 하나의 Stack Trace Block에 포함한다.

PEM 종료 이후 이어지는 Exception Header 또는 Stack Frame도 기존 Stack Trace 규칙에 따라 동일 Block에 포함한다.

In [395]:
def find_embedded_pem_end(
    text,
    search_start,
    search_end,
):
    begin_match = PEM_BEGIN_RE.search(
        text,
        search_start,
        search_end,
    )

    if begin_match is None:
        return None

    begin_marker = begin_match.group(0)

    end_marker = begin_marker.replace(
        "BEGIN",
        "END",
        1,
    )

    end_start = text.find(
        end_marker,
        begin_match.end(),
    )

    # BEGIN은 있지만 END가 없는 경우
    # 중간에서 임의로 분할하지 않는다.
    if end_start < 0:
        return len(text)

    return (
        end_start
        + len(end_marker)
    )

### 23.20 Embedded PEM Stack Trace Regression Test

Cross-boundary 문제를 발생시킨 실제 구조와 동일한 형태의 Test Input을 사용하여 Private Key 전체와 이후 Stack Trace가 하나의 Block으로 유지되는지 확인한다.

In [396]:
embedded_pem_stack_text = """java.lang.IllegalStateException: Unable to parse private key -----BEGIN PRIVATE KEY-----
DC0rGRpnRjW9gWLLydlsDGWSc4YD6heWW8XplCE7LFmqCO6B8PfIy6RG9VSZgkET
GX8TAQgwo0CsiwDSQWQVKtMV7kaM3sNiIO64jmDMMHxxLizlhOgH1kv9QPMug8Wu
-----END PRIVATE KEY-----
BuildException below EclipseDefaultExecutor.executeTargets
    at org.example.Executor.execute(Executor.java:100)
    at org.example.Service.run(Service.java:50)
"""


embedded_pem_blocks = build_blocks(
    embedded_pem_stack_text
)


print(
    "EMBEDDED PEM STACK TRACE"
)

print("=" * 60)

print(
    f"Blocks : "
    f"{len(embedded_pem_blocks)}"
)

print(
    "Types  :",
    [
        block["structure_type"]
        for block
        in embedded_pem_blocks
    ],
)

print(
    "Exact reconstruction :",
    "".join(
        block["text"]
        for block
        in embedded_pem_blocks
    )
    == embedded_pem_stack_text,
)

EMBEDDED PEM STACK TRACE
============================================================
Blocks : 1
Types  : ['JAVA_STACK_TRACE']
Exact reconstruction : True

## 24. Block-local Label Remapping

기존 Entity의 `start`, `end`는 원본 Sample Text 기준 Character Offset이다.

Structure-aware Block Builder를 적용하면 하나의 Sample이 여러 Block으로 분리될 수 있으므로, 각 Entity의 Character Span을 해당 Block 내부 좌표로 변환해야 한다.

예를 들어 원본 Text에서 Entity가 다음 위치에 존재한다고 가정한다.

```
Entity: 120 ~ 150
Block : 100 ~ 200
```

Block 내부에서는 다음과 같이 변환된다.

```
Local Entity: 20 ~ 50
```

이번 단계에서는 다음 작업을 수행한다.

* 원본 Character Span을 Block-local Character Span으로 변환
* 각 Entity가 정확히 하나의 Block에 배치되는지 검증
* `block_text[start:end] == entity["value"]` 검증
* 원본 Entity 수와 Block Entity 수가 동일한지 검증
* Block별 고유 ID 생성
* Train / Validation / Test용 Backbone-independent Block Dataset 생성

Challenge Test는 최종 평가용으로 동결되어 있으므로 현재 단계에서는 처리하지 않는다.

In [397]:
VALIDATION_PATH = Path(
    "../data/processed/splits/"
    "validation.jsonl"
)

TEST_PATH = Path(
    "../data/processed/splits/"
    "test.jsonl"
)


validation_records = load_jsonl(
    VALIDATION_PATH
)

test_records = load_jsonl(
    TEST_PATH
)


print(
    f"Train      : "
    f"{len(train_records):,}"
)

print(
    f"Validation : "
    f"{len(validation_records):,}"
)

print(
    f"Test       : "
    f"{len(test_records):,}"
)

Train      : 43,048
Validation : 4,951
Test       : 5,201

### 24.2 Entity Span Remapping

각 원본 Entity가 어느 Block에 포함되는지 확인한 뒤 원본 Character Offset에서 Block-local Character Offset으로 변환한다.

Entity가 어떤 Block에도 완전히 포함되지 않거나 두 개 이상의 Block에 동시에 포함되는 경우에는 오류로 처리한다.

Block-local Entity에서도 원본 Value와 Character Span이 정확히 일치해야 한다.

In [398]:
def remap_entity_to_block(
    entity,
    block,
):
    source_start = (
        block["source_start"]
    )

    source_end = (
        block["source_end"]
    )

    entity_start = (
        entity["start"]
    )

    entity_end = (
        entity["end"]
    )

    if not (
        entity_start >= source_start
        and entity_end <= source_end
    ):
        return None

    local_start = (
        entity_start
        - source_start
    )

    local_end = (
        entity_end
        - source_start
    )

    return {
        "start":
            local_start,

        "end":
            local_end,

        "label":
            entity["label"],

        "value":
            entity["value"],
    }

### 24.3 Block Record 생성

각 원본 Sample에 Block Builder를 적용하고 Block별 학습 Record를 생성한다.

각 Block에는 다음 정보를 저장한다.

- Block Text
- Block-local Entity Span
- 원본 Sample ID
- 원본 Character 위치
- Segment Mapping
- Structure Type
- 기존 Log Type
- 기존 Template Family Metadata

`log_type`은 이후 분석을 위한 Metadata로만 유지하며 모델 입력 Feature로 사용하지 않는다.

원본 Sample이 여러 Block으로 분리된 경우 각 Block에 새로운 고유 `sample_id`와 `template_id`를 부여한다.

In [399]:
def convert_record_to_blocks(
    record,
):
    source_text = (
        record["text"]
    )

    blocks = build_blocks(
        source_text
    )

    block_records = []

    assigned_entity_count = 0


    for block_index, block in enumerate(
        blocks
    ):
        local_entities = []

        for entity in record[
            "entities"
        ]:
            remapped_entity = (
                remap_entity_to_block(
                    entity,
                    block,
                )
            )

            if remapped_entity is None:
                continue

            local_start = (
                remapped_entity["start"]
            )

            local_end = (
                remapped_entity["end"]
            )

            block_value = (
                block["text"][
                    local_start:
                    local_end
                ]
            )

            if (
                block_value
                != remapped_entity[
                    "value"
                ]
            ):
                raise ValueError(
                    "Block-local entity span "
                    "does not match value: "
                    f"{record['sample_id']}"
                )

            local_entities.append(
                remapped_entity
            )

            assigned_entity_count += 1


        source_sample_type = (
            record.get(
                "sample_type"
            )
        )

        if local_entities:
            block_sample_type = (
                "positive"
            )

        elif (
            source_sample_type
            == "hard_negative"
        ):
            block_sample_type = (
                "hard_negative"
            )

        else:
            block_sample_type = (
                "clean"
            )


        source_sample_id = (
            record["sample_id"]
        )

        source_template_id = (
            record.get(
                "template_id"
            )
        )

        block_sample_id = (
            f"{source_sample_id}"
            f"__block_{block_index:02d}"
        )

        if source_template_id:
            block_template_id = (
                f"{source_template_id}"
                f"__block_{block_index:02d}"
            )

        else:
            block_template_id = None


        block_record = {
            key: value
            for key, value
            in record.items()
            if key not in {
                "text",
                "entities",
                "sample_id",
                "template_id",
                "sample_type",
            }
        }


        block_record.update(
            {
                "sample_id":
                    block_sample_id,

                "source_sample_id":
                    source_sample_id,

                "template_id":
                    block_template_id,

                "source_template_id":
                    source_template_id,

                "sample_type":
                    block_sample_type,

                "source_sample_type":
                    source_sample_type,

                "text":
                    block["text"],

                "entities":
                    local_entities,

                "structure_type":
                    block[
                        "structure_type"
                    ],

                "source_start":
                    block[
                        "source_start"
                    ],

                "source_end":
                    block[
                        "source_end"
                    ],

                "segments":
                    block[
                        "segments"
                    ],
            }
        )

        block_records.append(
            block_record
        )


    if (
        assigned_entity_count
        != len(record["entities"])
    ):
        raise ValueError(
            "Not all entities were assigned "
            "to exactly one block: "
            f"{record['sample_id']} "
            f"({assigned_entity_count} / "
            f"{len(record['entities'])})"
        )


    return block_records

In [400]:
train_blocks = []


for index, record in enumerate(
    train_records,
    start=1,
):
    record_blocks = (
        convert_record_to_blocks(
            record
        )
    )

    train_blocks.extend(
        record_blocks
    )

    if index % 5000 == 0:
        print(
            f"Processed "
            f"{index:,} / "
            f"{len(train_records):,}"
        )

Processed 5,000 / 43,048
Processed 10,000 / 43,048
Processed 15,000 / 43,048
Processed 20,000 / 43,048
Processed 25,000 / 43,048
Processed 30,000 / 43,048
Processed 35,000 / 43,048
Processed 40,000 / 43,048

### 24.5 Train Block Dataset 검증

Block-local Label Remapping 결과가 원본 Dataset의 Label 정보를 손실하지 않았는지 확인한다.

다음 조건을 검증한다.

* Block ID 중복 없음
* Block Text 중 빈 값 없음
* 모든 Character Span이 유효함
* `text[start:end] == value`
* 원본 Entity 수와 Block Entity 수 동일
* 원본 Sample을 구성하는 Block Text를 다시 합치면 원본 Text와 동일

In [401]:
def validate_block_records(
    source_records,
    block_records,
):
    block_ids = [
        record["sample_id"]
        for record in block_records
    ]

    duplicate_block_ids = (
        len(block_ids)
        - len(set(block_ids))
    )

    empty_blocks = 0

    invalid_spans = 0

    remapped_entity_count = 0


    for block in block_records:
        if not block["text"]:
            empty_blocks += 1

        for entity in block[
            "entities"
        ]:
            remapped_entity_count += 1

            start = entity["start"]
            end = entity["end"]

            if not (
                0
                <= start
                < end
                <= len(block["text"])
            ):
                invalid_spans += 1
                continue

            if (
                block["text"][
                    start:end
                ]
                != entity["value"]
            ):
                invalid_spans += 1


    original_entity_count = sum(
        len(record["entities"])
        for record in source_records
    )


    blocks_by_source = defaultdict(
        list
    )

    for block in block_records:
        blocks_by_source[
            block[
                "source_sample_id"
            ]
        ].append(
            block
        )


    source_lookup = {
        record["sample_id"]:
            record
        for record in source_records
    }


    reconstruction_errors = 0


    for source_sample_id, blocks in (
        blocks_by_source.items()
    ):
        blocks = sorted(
            blocks,
            key=lambda block:
                block["source_start"],
        )

        reconstructed = "".join(
            block["text"]
            for block in blocks
        )

        if (
            reconstructed
            != source_lookup[
                source_sample_id
            ]["text"]
        ):
            reconstruction_errors += 1


    return {
        "source_samples":
            len(source_records),

        "blocks":
            len(block_records),

        "duplicate_block_ids":
            duplicate_block_ids,

        "empty_blocks":
            empty_blocks,

        "original_entities":
            original_entity_count,

        "remapped_entities":
            remapped_entity_count,

        "invalid_spans":
            invalid_spans,

        "reconstruction_errors":
            reconstruction_errors,
    }

In [402]:
train_block_validation = (
    validate_block_records(
        train_records,
        train_blocks,
    )
)


print(
    "TRAIN BLOCK DATASET VALIDATION"
)

print("=" * 65)


for key, value in (
    train_block_validation
    .items()
):
    if isinstance(
        value,
        int,
    ):
        print(
            f"{key:<25} : "
            f"{value:,}"
        )

    else:
        print(
            f"{key:<25} : "
            f"{value}"
        )

TRAIN BLOCK DATASET VALIDATION
=================================================================
source_samples            : 43,048
blocks                    : 44,626
duplicate_block_ids       : 0
empty_blocks              : 0
original_entities         : 55,398
remapped_entities         : 55,398
invalid_spans             : 0
reconstruction_errors     : 0

### 24.6 Validation / Test Block Dataset 생성

Train Dataset에서 Block-local Label Remapping이 정상적으로 수행되는 것을 확인했다.

이제 동일한 Block Builder와 Label Remapping 로직을 Validation과 Test Dataset에도 적용한다.

Train, Validation, Test는 동일한 전처리 Pipeline을 사용해야 하며 각 Split 간 데이터 이동이나 재분할은 수행하지 않는다.

In [403]:
def convert_dataset_to_blocks(
    records,
    split_name,
):
    block_records = []

    for index, record in enumerate(
        records,
        start=1,
    ):
        record_blocks = (
            convert_record_to_blocks(
                record
            )
        )

        block_records.extend(
            record_blocks
        )

        if index % 2000 == 0:
            print(
                f"{split_name}: "
                f"{index:,} / "
                f"{len(records):,}"
            )

    return block_records

In [404]:
validation_blocks = (
    convert_dataset_to_blocks(
        validation_records,
        "Validation",
    )
)


test_blocks = (
    convert_dataset_to_blocks(
        test_records,
        "Test",
    )
)


print(
    f"Validation blocks : "
    f"{len(validation_blocks):,}"
)

print(
    f"Test blocks       : "
    f"{len(test_blocks):,}"
)

Validation: 2,000 / 4,951
Validation: 4,000 / 4,951
Test: 2,000 / 5,201
Test: 4,000 / 5,201
Validation blocks : 5,163
Test blocks       : 5,385

### 24.7 Validation / Test Block Dataset 검증

Validation과 Test Dataset에도 Train과 동일한 검증을 수행한다.

다음 조건을 확인한다.

- 모든 원본 Entity가 정확히 하나의 Block으로 이동했는지
- Block-local Span이 유효한지
- `text[start:end] == value`인지
- Block ID가 중복되지 않는지
- Block을 다시 합쳤을 때 원본 Sample Text와 동일한지

In [405]:
validation_block_validation = (
    validate_block_records(
        validation_records,
        validation_blocks,
    )
)


test_block_validation = (
    validate_block_records(
        test_records,
        test_blocks,
    )
)

In [406]:
def print_block_validation(
    title,
    result,
):
    print(title)

    print("=" * 65)

    for key, value in (
        result.items()
    ):
        if isinstance(
            value,
            int,
        ):
            print(
                f"{key:<25} : "
                f"{value:,}"
            )

        else:
            print(
                f"{key:<25} : "
                f"{value}"
            )

    print()

In [407]:
print_block_validation(
    "VALIDATION BLOCK DATASET VALIDATION",
    validation_block_validation,
)


print_block_validation(
    "TEST BLOCK DATASET VALIDATION",
    test_block_validation,
)

VALIDATION BLOCK DATASET VALIDATION
=================================================================
source_samples            : 4,951
blocks                    : 5,163
duplicate_block_ids       : 0
empty_blocks              : 0
original_entities         : 6,432
remapped_entities         : 6,432
invalid_spans             : 0
reconstruction_errors     : 0

TEST BLOCK DATASET VALIDATION
=================================================================
source_samples            : 5,201
blocks                    : 5,385
duplicate_block_ids       : 0
empty_blocks              : 0
original_entities         : 6,867
remapped_entities         : 6,867
invalid_spans             : 0
reconstruction_errors     : 0

### 24.8 Split 간 Block Leakage 검증

기존 Dataset은 `template_family_id`를 기준으로 Train, Validation, Test를 분리했다.

Block Dataset에서도 동일한 Split 경계가 유지되는지 확인한다.

Block 생성 과정에서 기존 `template_family_id`를 그대로 상속하므로 서로 다른 Split 사이에 동일한 Template Family가 존재해서는 안 된다.

In [408]:
def get_family_ids(
    records,
):
    return {
        record[
            "template_family_id"
        ]
        for record in records
        if record.get(
            "template_family_id"
        )
        is not None
    }


train_block_families = (
    get_family_ids(
        train_blocks
    )
)

validation_block_families = (
    get_family_ids(
        validation_blocks
    )
)

test_block_families = (
    get_family_ids(
        test_blocks
    )
)

In [409]:
train_validation_overlap = (
    train_block_families
    & validation_block_families
)

train_test_overlap = (
    train_block_families
    & test_block_families
)

validation_test_overlap = (
    validation_block_families
    & test_block_families
)


print(
    "BLOCK SPLIT FAMILY LEAKAGE"
)

print("=" * 60)

print(
    f"Train ↔ Validation : "
    f"{len(train_validation_overlap):,}"
)

print(
    f"Train ↔ Test       : "
    f"{len(train_test_overlap):,}"
)

print(
    f"Validation ↔ Test  : "
    f"{len(validation_test_overlap):,}"
)

BLOCK SPLIT FAMILY LEAKAGE
============================================================
Train ↔ Validation : 0
Train ↔ Test       : 0
Validation ↔ Test  : 0

### 24.9 Backbone-independent Block Dataset 저장

Block Builder와 Character Span Remapping 결과는 아직 특정 Transformer Tokenizer에 종속되지 않는다.

따라서 Train, Validation, Test Block Dataset을 Backbone-independent Dataset으로 저장한다.

이후 Tokenizer 비교와 BIO Label Alignment는 이 Block Dataset을 기준으로 수행한다.

Challenge Test는 개발 과정에서 반복적으로 사용하지 않기 위해 현재 저장 대상에서 제외한다.

In [410]:
BLOCK_OUTPUT_DIR = Path(
    "../data/processed/blocks"
)

BLOCK_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


BLOCK_PATHS = {
    "train":
        BLOCK_OUTPUT_DIR
        / "train_blocks.jsonl",

    "validation":
        BLOCK_OUTPUT_DIR
        / "validation_blocks.jsonl",

    "test":
        BLOCK_OUTPUT_DIR
        / "test_blocks.jsonl",
}

In [411]:
def save_jsonl(
    records,
    path,
):
    with path.open(
        "w",
        encoding="utf-8",
    ) as f:
        for record in records:
            f.write(
                json.dumps(
                    record,
                    ensure_ascii=False,
                )
                + "\n"
            )

In [412]:
save_jsonl(
    train_blocks,
    BLOCK_PATHS["train"],
)

save_jsonl(
    validation_blocks,
    BLOCK_PATHS["validation"],
)

save_jsonl(
    test_blocks,
    BLOCK_PATHS["test"],
)


for split_name, path in (
    BLOCK_PATHS.items()
):
    print(
        f"{split_name:<10} "
        f"{path}"
    )

train      ../data/processed/blocks/train_blocks.jsonl
validation ../data/processed/blocks/validation_blocks.jsonl
test       ../data/processed/blocks/test_blocks.jsonl

## 25. Tokenizer 후보 비교

Block Dataset이 확정되었으므로 Transformer Backbone 후보의 Tokenizer를 실제 Dataset에 적용하여 입력 길이를 비교한다.

Character Length만으로는 Transformer의 실제 입력 크기를 알 수 없다.

특히 다음과 같은 문자열은 Tokenizer에 따라 Token 분할 방식이 크게 달라질 수 있다.

* Base64
* Hexadecimal Token
* JWT
* API Key
* UUID
* URL Encoding
* 한글
* Connection String
* Private Key

따라서 모델을 선택하기 전에 실제 Block Dataset을 Tokenize하여 길이 분포를 비교한다.

이번 단계에서는 다음 항목을 확인한다.

* Block Token Length
* Log Type별 Token Length
* Entity Token Length
* Entity 종류별 Token Length
* P50 / P95 / P99 / Max
* 512 / 1024 / 2048 Token 초과 비율
* 특히 긴 `PRIVATE_KEY`, `TOKEN`, `SECRET`, `CONNECTION_STRING`의 Token Length

Tokenizer 분석 결과를 바탕으로 이후 `max_length`와 Sliding Window 정책을 결정한다.

### 25.1 Tokenizer 후보 정의

현재 단계에서는 다음 네 Tokenizer를 비교한다.

- mmBERT
- XLM-RoBERTa
- DeBERTa-v3
- ModernBERT

Tokenizer 비교 결과는 Backbone을 최종 선택하기 위한 근거로 사용한다.

이 단계에서 네 모델을 모두 학습하는 것은 아니다.

In [413]:
TOKENIZER_CANDIDATES = {
    "mmbert":
        "jhu-clsp/mmBERT-base",

    "xlm_roberta":
        "FacebookAI/xlm-roberta-base",

    "deberta_v3":
        "microsoft/deberta-v3-base",

    "modernbert":
        "answerdotai/ModernBERT-base",
}

In [414]:
import transformers

print(
    f"Transformers version : "
    f"{transformers.__version__}"
)

Transformers version : 5.15.0

In [415]:
from transformers import AutoTokenizer

### 25.3 Tokenizer 로드

각 Backbone의 Fast Tokenizer를 로드한다.

이후 Character Span과 Token Span을 연결하기 위해 `offset_mapping`이 필요하므로 Fast Tokenizer 사용 여부도 함께 확인한다.

In [419]:
import sys
import importlib.util

print(
    "Python executable :",
    sys.executable,
)

print(
    "SentencePiece :",
    importlib.util.find_spec(
        "sentencepiece"
    ),
)

Python executable : /opt/anaconda3/envs/sensitive-masking/bin/python
SentencePiece : ModuleSpec(name='sentencepiece', loader=<_frozen_importlib_external.SourceFileLoader object at 0x349f4bf10>, origin='/opt/anaconda3/envs/sensitive-masking/lib/python3.11/site-packages/sentencepiece/__init__.py', submodule_search_locations=['/opt/anaconda3/envs/sensitive-masking/lib/python3.11/site-packages/sentencepiece'])

In [420]:
import sys
import subprocess


subprocess.check_call(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--upgrade",
        "sentencepiece",
        "protobuf",
    ]
)

Requirement already satisfied: sentencepiece in /opt/anaconda3/envs/sensitive-masking/lib/python3.11/site-packages (0.2.2)
Requirement already satisfied: protobuf in /opt/anaconda3/envs/sensitive-masking/lib/python3.11/site-packages (7.35.1)

0

In [1]:
import sys
import sentencepiece
import transformers

from transformers.utils import is_sentencepiece_available

print("Python:", sys.executable)
print("SentencePiece version:", sentencepiece.__version__)
print("Transformers version:", transformers.__version__)
print(
    "Transformers detects SentencePiece:",
    is_sentencepiece_available(),
)

Python: /opt/anaconda3/envs/sensitive-masking/bin/python
SentencePiece version: 0.2.2
Transformers version: 5.15.0
Transformers detects SentencePiece: True

In [2]:
from transformers import AutoTokenizer


deberta_tokenizer = (
    AutoTokenizer.from_pretrained(
        "microsoft/deberta-v3-base",
        use_fast=True,
    )
)


print(
    "Tokenizer class:",
    type(deberta_tokenizer).__name__,
)

print(
    "Fast tokenizer:",
    deberta_tokenizer.is_fast,
)

print(
    "Vocab size:",
    f"{deberta_tokenizer.vocab_size:,}",
)

print(
    "Model max length:",
    deberta_tokenizer.model_max_length,
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Tokenizer class: DebertaV2Tokenizer
Fast tokenizer: True
Vocab size: 128,000
Model max length: 1000000000000000019884624838656

In [4]:
TOKENIZER_CANDIDATES = {
    "mmbert":
        "jhu-clsp/mmBERT-base",

    "xlm_roberta":
        "FacebookAI/xlm-roberta-base",

    "deberta_v3":
        "microsoft/deberta-v3-base",

    "modernbert":
        "answerdotai/ModernBERT-base",
}

In [5]:
from transformers import (
    AutoTokenizer,
    AutoConfig,
)


tokenizers = {}
model_configs = {}


for name, model_name in (
    TOKENIZER_CANDIDATES.items()
):
    print(
        f"Loading {name}: "
        f"{model_name}"
    )

    tokenizer = (
        AutoTokenizer.from_pretrained(
            model_name,
            use_fast=True,
        )
    )

    config = (
        AutoConfig.from_pretrained(
            model_name
        )
    )

    tokenizers[name] = tokenizer
    model_configs[name] = config

    tokenizer_max_length = (
        tokenizer.model_max_length
    )

    model_max_positions = getattr(
        config,
        "max_position_embeddings",
        None,
    )

    print(
        f"  Tokenizer class : "
        f"{type(tokenizer).__name__}"
    )

    print(
        f"  Fast tokenizer  : "
        f"{tokenizer.is_fast}"
    )

    print(
        f"  Vocab size      : "
        f"{tokenizer.vocab_size:,}"
    )

    print(
        f"  Tokenizer max   : "
        f"{tokenizer_max_length}"
    )

    print(
        f"  Model positions : "
        f"{model_max_positions}"
    )

    print()

Loading mmbert: jhu-clsp/mmBERT-base
  Tokenizer class : TokenizersBackend
  Fast tokenizer  : True
  Vocab size      : 256,000
  Tokenizer max   : 8192
  Model positions : 8192

Loading xlm_roberta: FacebookAI/xlm-roberta-base
  Tokenizer class : XLMRobertaTokenizer
  Fast tokenizer  : True
  Vocab size      : 250,002
  Tokenizer max   : 512
  Model positions : 514

Loading deberta_v3: microsoft/deberta-v3-base
  Tokenizer class : DebertaV2Tokenizer
  Fast tokenizer  : True
  Vocab size      : 128,000
  Tokenizer max   : 1000000000000000019884624838656
  Model positions : 512

Loading modernbert: answerdotai/ModernBERT-base

config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/20.8k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.13M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

  Tokenizer class : TokenizersBackend
  Fast tokenizer  : True
  Vocab size      : 50,280
  Tokenizer max   : 8192
  Model positions : 8192

### 25.4 Block Dataset 다시 로드

Kernel Restart로 기존 Python 변수가 초기화되었으므로 저장해둔 Backbone-independent Block Dataset을 다시 로드한다.

Tokenizer 비교 단계에서는 Train Block Dataset만 사용한다.

Validation과 Test는 Tokenizer 및 `max_length` 정책이 확정된 이후 동일한 Pipeline을 적용한다.

In [6]:
from pathlib import Path

import json
import numpy as np
import pandas as pd


BLOCK_OUTPUT_DIR = Path(
    "../data/processed/blocks"
)


def load_jsonl(path):
    records = []

    with path.open(
        "r",
        encoding="utf-8",
    ) as f:
        for line in f:
            if line.strip():
                records.append(
                    json.loads(line)
                )

    return records


train_blocks = load_jsonl(
    BLOCK_OUTPUT_DIR
    / "train_blocks.jsonl"
)


print(
    f"Train blocks : "
    f"{len(train_blocks):,}"
)

Train blocks : 44,626

### 25.5 Block Token Length 분석

각 Tokenizer를 이용하여 Train Block 전체를 truncation 없이 Tokenize한다.

Block Token Length에는 실제 모델 입력에 포함되는 Special Token도 포함한다.

한 번에 전체 Dataset을 Tokenize하면 메모리 사용량이 증가할 수 있으므로 Batch 단위로 처리한다.

다음 통계를 비교한다.

- Mean
- P50
- P95
- P99
- Max
- 512 Token 초과 비율
- 1024 Token 초과 비율
- 2048 Token 초과 비율

In [7]:
def get_block_token_lengths(
    tokenizer,
    records,
    batch_size=256,
):
    lengths = []

    texts = [
        record["text"]
        for record in records
    ]

    for start in range(
        0,
        len(texts),
        batch_size,
    ):
        batch_texts = texts[
            start:
            start + batch_size
        ]

        encoded = tokenizer(
            batch_texts,
            add_special_tokens=True,
            truncation=False,
            padding=False,
            return_length=True,
            return_attention_mask=False,
            return_token_type_ids=False,
        )

        lengths.extend(
            encoded["length"]
        )

        processed = min(
            start + batch_size,
            len(texts),
        )

        if (
            processed % 5000 < batch_size
            or processed == len(texts)
        ):
            print(
                f"  {processed:,} / "
                f"{len(texts):,}"
            )

    return np.array(
        lengths
    )

In [8]:
block_token_lengths = {}


for name, tokenizer in (
    tokenizers.items()
):
    print(
        "\n"
        + "=" * 60
    )

    print(
        f"Tokenizer : {name}"
    )

    print("=" * 60)

    block_token_lengths[
        name
    ] = (
        get_block_token_lengths(
            tokenizer,
            train_blocks,
        )
    )

============================================================
Tokenizer : mmbert
============================================================
  5,120 / 44,626
  10,240 / 44,626
  15,104 / 44,626
  20,224 / 44,626
  25,088 / 44,626
  30,208 / 44,626
  35,072 / 44,626
  40,192 / 44,626
  44,626 / 44,626

============================================================
Tokenizer : xlm_roberta
============================================================
  5,120 / 44,626
  10,240 / 44,626
  15,104 / 44,626
  20,224 / 44,626
  25,088 / 44,626
  30,208 / 44,626

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (810 > 512). Running this sequence through the model will result in indexing errors

  35,072 / 44,626
  40,192 / 44,626
  44,626 / 44,626

============================================================
Tokenizer : deberta_v3
============================================================
  5,120 / 44,626
  10,240 / 44,626
  15,104 / 44,626
  20,224 / 44,626
  25,088 / 44,626
  30,208 / 44,626
  35,072 / 44,626
  40,192 / 44,626
  44,626 / 44,626

============================================================
Tokenizer : modernbert
============================================================
  5,120 / 44,626
  10,240 / 44,626
  15,104 / 44,626
  20,224 / 44,626
  25,088 / 44,626
  30,208 / 44,626
  35,072 / 44,626
  40,192 / 44,626
  44,626 / 44,626

In [9]:
def summarize_lengths(
    lengths,
):
    return {
        "mean":
            np.mean(lengths),

        "p50":
            np.percentile(
                lengths,
                50,
            ),

        "p95":
            np.percentile(
                lengths,
                95,
            ),

        "p99":
            np.percentile(
                lengths,
                99,
            ),

        "max":
            np.max(lengths),

        ">512":
            np.mean(
                lengths > 512
            ) * 100,

        ">1024":
            np.mean(
                lengths > 1024
            ) * 100,

        ">2048":
            np.mean(
                lengths > 2048
            ) * 100,
    }

In [10]:
block_length_summary = (
    pd.DataFrame(
        {
            name:
                summarize_lengths(
                    lengths
                )
            for name, lengths
            in block_token_lengths.items()
        }
    )
    .T
)


block_length_summary = (
    block_length_summary
    .round(2)
)


block_length_summary

               mean   p50    p95     p99     max  >512  >1024  >2048
mmbert       141.89  82.0  655.0  751.00   985.0  8.42   0.00    0.0
xlm_roberta  140.04  81.0  731.0  858.00  1183.0  8.65   0.06    0.0
deberta_v3   127.29  83.0  590.0  708.00   927.0  8.15   0.00    0.0
modernbert   127.03  69.0  626.0  739.75   957.0  8.32   0.00    0.0

### 25.6 Block Token Length 분석 결과

Train Block 44,626개를 네 Tokenizer로 분석한 결과 모든 Tokenizer에서 약 8%의 Block이 512 Token을 초과했다.

따라서 최대 입력 길이가 약 512 Token인 Backbone을 사용하는 경우 Sliding Window 처리가 필요하다.

반면 mmBERT와 ModernBERT에서는 현재 Train Dataset의 모든 Block이 1024 Token 이내에 포함되었다.

주요 결과는 다음과 같다.

| Tokenizer | P95 | P99 | Max | 512 초과 |
| --- | ---: | ---: | ---: | ---: |
| mmBERT | 655 | 751 | 985 | 8.42% |
| XLM-RoBERTa | 731 | 858 | 1183 | 8.65% |
| DeBERTa-v3 | 590 | 708 | 927 | 8.15% |
| ModernBERT | 626 | 740 | 957 | 8.32% |

DeBERTa-v3와 ModernBERT가 상대적으로 적은 Token 수로 Block을 표현했으며, XLM-RoBERTa는 긴 Block에서 Token 수가 가장 많았다.

다만 Block 전체 길이만으로 Backbone을 결정하지 않는다.

민감정보 Entity 자체의 Token 길이와 긴 Entity의 분할 가능성을 추가로 확인한 뒤 `max_length`와 Sliding Window 정책을 결정한다.

### 25.7 Log Type별 Token Length 비교

전체 Block Token Length만 확인하면 긴 Java Stack Trace의 영향으로 다른 Log Type의 특성이 가려질 수 있다.

따라서 각 Tokenizer에서 Log Type별 P95와 P99 Token Length를 비교한다.

`log_type`은 모델 입력 Feature가 아니라 분석 Metadata로만 사용한다.

In [11]:
log_types = [
    record["log_type"]
    for record in train_blocks
]


log_type_token_rows = []


for tokenizer_name, lengths in (
    block_token_lengths.items()
):
    temp_df = pd.DataFrame(
        {
            "log_type":
                log_types,

            "token_length":
                lengths,
        }
    )

    grouped = (
        temp_df
        .groupby("log_type")[
            "token_length"
        ]
    )

    for log_type, values in grouped:
        log_type_token_rows.append(
            {
                "tokenizer":
                    tokenizer_name,

                "log_type":
                    log_type,

                "mean":
                    values.mean(),

                "p95":
                    np.percentile(
                        values,
                        95,
                    ),

                "p99":
                    np.percentile(
                        values,
                        99,
                    ),

                "max":
                    values.max(),
            }
        )


log_type_token_df = (
    pd.DataFrame(
        log_type_token_rows
    )
)


log_type_token_df[
    [
        "mean",
        "p95",
        "p99",
        "max",
    ]
] = (
    log_type_token_df[
        [
            "mean",
            "p95",
            "p99",
            "max",
        ]
    ]
    .round(1)
)


log_type_token_df

      tokenizer          log_type   mean    p95    p99   max
0        mmbert   APPLICATION_LOG   98.6  207.0  232.0   280
1        mmbert        ENV_CONFIG   60.0  112.0  210.0   221
2        mmbert       HTTP_ACCESS  137.6  171.0  192.0   332
3        mmbert       HTTP_HEADER   76.0  123.0  133.0   164
4        mmbert  JAVA_STACK_TRACE  428.0  768.0  862.0   985
5        mmbert          JSON_LOG   91.8  155.0  212.0   229
6        mmbert        SYSTEM_LOG   54.8   87.0  101.8   127
7   xlm_roberta   APPLICATION_LOG   72.2  136.0  226.0   243
8   xlm_roberta        ENV_CONFIG   60.7  129.0  235.0   249
9   xlm_roberta       HTTP_ACCESS   99.6  127.0  144.0   256
10  xlm_roberta       HTTP_HEADER   71.3  121.0  136.0   153
11  xlm_roberta  JAVA_STACK_TRACE  481.5  875.0  975.0  1183
12  xlm_roberta          JSON_LOG  107.1  174.0  250.0   265
13  xlm_roberta        SYSTEM_LOG   39.5   66.0   82.8   105
14   deberta_v3   APPLICATION_LOG   73.8  152.0  223.0   242
15   deberta_v3        ENV_CONFIG   57.9  134.0  234.0   244
16   deberta_v3       HTTP_ACCESS  107.1  137.0  156.0   267
17   deberta_v3       HTTP_HEADER   65.6  111.0  126.0   147
18   deberta_v3  JAVA_STACK_TRACE  392.9  729.0  830.0   927
19   deberta_v3          JSON_LOG  108.5  171.0  249.0   268
20   deberta_v3        SYSTEM_LOG   39.7   67.0   82.8   109
21   modernbert   APPLICATION_LOG   75.3  157.0  216.0   238
22   modernbert        ENV_CONFIG   59.3  122.0  228.0   242
23   modernbert       HTTP_ACCESS  109.6  140.0  160.0   284
24   modernbert       HTTP_HEADER   70.1  119.0  134.0   156
25   modernbert  JAVA_STACK_TRACE  413.3  757.0  863.5   957
26   modernbert          JSON_LOG   81.7  142.0  230.0   248
27   modernbert        SYSTEM_LOG   39.7   66.0   82.8   107

### 25.8 Entity Token Length 분석

Entity Value를 독립적으로 Tokenize하는 대신 실제 Block 전체를 Tokenize하고 `offset_mapping`을 이용하여 각 Entity Character Span과 겹치는 Token 수를 계산한다.

이를 통해 실제 Token Classification 학습 시 Entity 하나가 몇 개의 Token으로 표현되는지 확인한다.

특히 다음 Entity를 중점적으로 확인한다.

- PRIVATE_KEY
- TOKEN
- SECRET
- CONNECTION_STRING

긴 Entity가 `max_length`보다 길거나 Window 내부에서 자주 분리되면 이후 Sliding Window 및 Label Alignment 정책에 직접적인 영향을 준다.

In [12]:
def collect_entity_token_lengths(
    tokenizer,
    records,
):
    entity_lengths = []

    for index, record in enumerate(
        records,
        start=1,
    ):
        encoded = tokenizer(
            record["text"],
            add_special_tokens=True,
            truncation=False,
            return_offsets_mapping=True,
            return_attention_mask=False,
            return_token_type_ids=False,
        )

        offsets = encoded[
            "offset_mapping"
        ]

        for entity in record[
            "entities"
        ]:
            entity_start = (
                entity["start"]
            )

            entity_end = (
                entity["end"]
            )

            token_count = 0

            for token_start, token_end in offsets:
                # Special token
                if (
                    token_start == 0
                    and token_end == 0
                ):
                    continue

                # Entity span과 Token span이
                # 한 글자라도 겹치는 경우
                if (
                    token_start
                    < entity_end
                    and token_end
                    > entity_start
                ):
                    token_count += 1

            entity_lengths.append(
                {
                    "label":
                        entity["label"],

                    "token_length":
                        token_count,
                }
            )

        if (
            index % 5000 == 0
            or index == len(records)
        ):
            print(
                f"  {index:,} / "
                f"{len(records):,}"
            )

    return pd.DataFrame(
        entity_lengths
    )

In [13]:
entity_token_stats = {}


for name, tokenizer in (
    tokenizers.items()
):
    print(
        "\n"
        + "=" * 60
    )

    print(
        f"Entity analysis : {name}"
    )

    print("=" * 60)

    entity_token_stats[
        name
    ] = (
        collect_entity_token_lengths(
            tokenizer,
            train_blocks,
        )
    )

============================================================
Entity analysis : mmbert
============================================================
  5,000 / 44,626
  10,000 / 44,626
  15,000 / 44,626
  20,000 / 44,626
  25,000 / 44,626
  30,000 / 44,626
  35,000 / 44,626
  40,000 / 44,626
  44,626 / 44,626

============================================================
Entity analysis : xlm_roberta
============================================================
  5,000 / 44,626
  10,000 / 44,626
  15,000 / 44,626
  20,000 / 44,626
  25,000 / 44,626
  30,000 / 44,626
  35,000 / 44,626
  40,000 / 44,626
  44,626 / 44,626

============================================================
Entity analysis : deberta_v3
============================================================
  5,000 / 44,626
  10,000 / 44,626
  15,000 / 44,626
  20,000 / 44,626
  25,000 / 44,626
  30,000 / 44,626
  35,000 / 44,626
  40,000 / 44,626
  44,626 / 44,626

============================================================
Entity analysis : modernbert
============================================================
  5,000 / 44,626
  10,000 / 44,626
  15,000 / 44,626
  20,000 / 44,626
  25,000 / 44,626
  30,000 / 44,626
  35,000 / 44,626
  40,000 / 44,626
  44,626 / 44,626

In [14]:
entity_summary_rows = []


for tokenizer_name, entity_df in (
    entity_token_stats.items()
):
    for label, group in (
        entity_df
        .groupby("label")
    ):
        values = (
            group[
                "token_length"
            ]
        )

        entity_summary_rows.append(
            {
                "tokenizer":
                    tokenizer_name,

                "label":
                    label,

                "count":
                    len(values),

                "mean":
                    values.mean(),

                "p50":
                    np.percentile(
                        values,
                        50,
                    ),

                "p95":
                    np.percentile(
                        values,
                        95,
                    ),

                "p99":
                    np.percentile(
                        values,
                        99,
                    ),

                "max":
                    values.max(),
            }
        )


entity_length_summary = (
    pd.DataFrame(
        entity_summary_rows
    )
)


entity_length_summary[
    [
        "mean",
        "p50",
        "p95",
        "p99",
        "max",
    ]
] = (
    entity_length_summary[
        [
            "mean",
            "p50",
            "p95",
            "p99",
            "max",
        ]
    ]
    .round(1)
)


entity_length_summary

      tokenizer              label  count   mean    p50    p95    p99  max
0        mmbert            API_KEY   2969   26.1   28.0   37.0   38.0   40
1        mmbert  CONNECTION_STRING   1325   35.6   36.0   43.0   44.0   46
2        mmbert              EMAIL   1994   10.0   10.0   18.0   20.0   21
3        mmbert         IP_ADDRESS  16506   14.4   14.0   21.0   22.0   22
4        mmbert        PARAM_VALUE  18280   10.7    9.0   35.0   43.0   43
5        mmbert           PASSWORD   1490   16.9   15.0   30.0   31.0   32
6        mmbert             PERSON   1958    2.6    3.0    3.0    3.0    3
7        mmbert              PHONE    913   14.2   15.0   16.0   16.0   16
8        mmbert        PRIVATE_KEY   1141  147.9  186.0  201.0  205.0  212
9        mmbert             SECRET   2170   35.5   32.0   57.0   60.0   62
10       mmbert         SESSION_ID   3555   30.1   31.0   35.0   36.0   40
11       mmbert              TOKEN   3097   45.3   45.0   58.0   61.0   63
12  xlm_roberta            API_KEY   2969   26.3   27.0   38.0   40.0   43
13  xlm_roberta  CONNECTION_STRING   1325   37.1   37.0   46.0   47.0   50
14  xlm_roberta              EMAIL   1994   10.8   10.0   16.0   18.1   22
15  xlm_roberta         IP_ADDRESS  16506    7.4    7.0   15.0   18.0   22
16  xlm_roberta        PARAM_VALUE  18280    8.1    4.0   26.0   33.0   33
17  xlm_roberta           PASSWORD   1490   15.4   17.0   22.0   23.0   27
18  xlm_roberta             PERSON   1958    3.0    3.0    4.0    4.0    5
19  xlm_roberta              PHONE    913    6.2    7.0    8.0    8.0    8
20  xlm_roberta        PRIVATE_KEY   1141  169.0  208.0  225.0  230.0  236
21  xlm_roberta             SECRET   2170   34.6   33.0   44.0   47.0   51
22  xlm_roberta         SESSION_ID   3555   26.6   25.0   38.0   40.0   45
23  xlm_roberta              TOKEN   3097   46.7   43.0   62.0   65.0   68
24   deberta_v3            API_KEY   2969   25.3   26.0   37.0   39.0   42
25   deberta_v3  CONNECTION_STRING   1325   36.1   35.0   44.0   46.0   48
26   deberta_v3              EMAIL   1994    8.8    9.0   14.0   15.0   17
27   deberta_v3         IP_ADDRESS  16506    8.0    7.0   15.0   18.0   22
28   deberta_v3        PARAM_VALUE  18280    8.4    4.0   27.0   38.0   38
29   deberta_v3           PASSWORD   1490   14.6   16.0   21.0   22.0   26
30   deberta_v3             PERSON   1958    2.6    3.0    3.0    3.0    3
31   deberta_v3              PHONE    913    7.3    7.0   10.0   10.0   10
32   deberta_v3        PRIVATE_KEY   1141  171.5  210.0  226.0  231.0  239
33   deberta_v3             SECRET   2170   33.1   32.0   43.0   45.0   50
34   deberta_v3         SESSION_ID   3555   25.7   24.0   37.0   39.0   43
35   deberta_v3              TOKEN   3097   45.0   41.0   60.0   63.0   67
36   modernbert            API_KEY   2969   26.0   27.0   37.0   40.0   42
37   modernbert  CONNECTION_STRING   1325   34.1   34.0   42.0   44.0   45
38   modernbert              EMAIL   1994    8.8    9.0   14.0   15.0   17
39   modernbert         IP_ADDRESS  16506    7.9    7.0   14.0   17.0   21
40   modernbert        PARAM_VALUE  18280    9.1    6.0   27.0   38.0   38
41   modernbert           PASSWORD   1490   15.0   17.0   21.0   23.0   26
42   modernbert             PERSON   1958    5.1    6.0    8.0    9.0    9
43   modernbert              PHONE    913    7.6    7.0   10.0   10.0   11
44   modernbert        PRIVATE_KEY   1141  161.7  203.0  219.0  223.0  231
45   modernbert             SECRET   2170   33.7   33.0   43.0   45.0   49
46   modernbert         SESSION_ID   3555   26.1   25.0   37.0   39.0   43
47   modernbert              TOKEN   3097   45.7   42.0   61.0   64.0   68

In [15]:
FOCUS_ENTITIES = [
    "PRIVATE_KEY",
    "TOKEN",
    "SECRET",
    "CONNECTION_STRING",
]


focus_entity_summary = (
    entity_length_summary[
        entity_length_summary[
            "label"
        ].isin(
            FOCUS_ENTITIES
        )
    ]
    .sort_values(
        [
            "label",
            "tokenizer",
        ]
    )
    .reset_index(
        drop=True
    )
)


focus_entity_summary

      tokenizer              label  count   mean    p50    p95    p99  max
0    deberta_v3  CONNECTION_STRING   1325   36.1   35.0   44.0   46.0   48
1        mmbert  CONNECTION_STRING   1325   35.6   36.0   43.0   44.0   46
2    modernbert  CONNECTION_STRING   1325   34.1   34.0   42.0   44.0   45
3   xlm_roberta  CONNECTION_STRING   1325   37.1   37.0   46.0   47.0   50
4    deberta_v3        PRIVATE_KEY   1141  171.5  210.0  226.0  231.0  239
5        mmbert        PRIVATE_KEY   1141  147.9  186.0  201.0  205.0  212
6    modernbert        PRIVATE_KEY   1141  161.7  203.0  219.0  223.0  231
7   xlm_roberta        PRIVATE_KEY   1141  169.0  208.0  225.0  230.0  236
8    deberta_v3             SECRET   2170   33.1   32.0   43.0   45.0   50
9        mmbert             SECRET   2170   35.5   32.0   57.0   60.0   62
10   modernbert             SECRET   2170   33.7   33.0   43.0   45.0   49
11  xlm_roberta             SECRET   2170   34.6   33.0   44.0   47.0   51
12   deberta_v3              TOKEN   3097   45.0   41.0   60.0   63.0   67
13       mmbert              TOKEN   3097   45.3   45.0   58.0   61.0   63
14   modernbert              TOKEN   3097   45.7   42.0   61.0   64.0   68
15  xlm_roberta              TOKEN   3097   46.7   43.0   62.0   65.0   68

### 25.10 Tokenizer 비교 결과

Train Block과 Entity의 실제 Token Length를 분석한 결과 다음과 같은 특징을 확인했다.

Block 전체에서는 모든 Tokenizer에서 약 8%의 Sample이 512 Token을 초과했다.

특히 Java Stack Trace가 긴 입력의 대부분을 차지했으며, mmBERT 기준 Java Stack Trace의 P95는 768 Token, P99는 862 Token, 최대 길이는 985 Token이었다.

반면 민감정보 Entity 자체는 512 Token보다 충분히 짧았다.

주요 긴 Entity의 최대 Token Length는 다음 범위였다.

* `PRIVATE_KEY`: 212 ~ 239 Token
* `TOKEN`: 63 ~ 68 Token
* `SECRET`: 49 ~ 62 Token
* `CONNECTION_STRING`: 45 ~ 50 Token

따라서 현재 Dataset에서 512 Token을 초과하는 주요 원인은 Entity 자체가 아니라 Entity 주변의 긴 Log Context이다.

Primary Backbone은 mmBERT로 결정한다.

mmBERT를 선택한 이유는 다음과 같다.

* Multilingual Encoder이므로 한글과 영어가 혼합된 입력에 적합하다.
* 최대 8,192 Token의 긴 Sequence를 지원한다.
* 현재 Train Block은 모두 1,024 Token 이내에 포함된다.
* `PRIVATE_KEY` 역시 최대 212 Token으로 비교적 효율적으로 Tokenize되었다.

XLM-RoBERTa는 이후 Multilingual Baseline 비교 모델로 유지한다.

실제 학습에서는 불필요하게 8,192 Token 전체를 사용하지 않고, Train/Validation의 실제 길이 분포를 바탕으로 더 작은 `max_length`를 결정한다.

실제 서비스 입력은 학습 Dataset보다 길 수 있으므로 mmBERT를 사용하더라도 Sliding Window 기능은 유지한다.

## 26. max_length 및 Sliding Window 정책

Tokenizer 비교 결과 Primary Backbone 후보인 mmBERT에서는 현재 Train Block의 최대 길이가 985 Token이었다.

하지만 실제 서비스 입력은 현재 Dataset보다 길 수 있으므로 단순히 현재 최대 길이만 기준으로 입력 길이를 결정하지 않는다.

이번 단계에서는 Train과 Validation Dataset을 이용하여 다음 정책을 결정한다.

* `max_length`
* `stride`
* Sliding Window 적용 조건
* Entity가 Window 경계에서 분할되는 경우의 Label 처리

Test와 Challenge Test는 정책 결정에 사용하지 않는다.

먼저 `max_length` 후보별 실제 Overflow 비율을 비교한 뒤 Sliding Window에서 Entity가 어떻게 분할되는지 분석한다.

### 26.1 Validation Block Token Length 분석

Tokenizer와 입력 길이 정책은 Train뿐 아니라 Validation에서도 안정적으로 동작해야 한다.

따라서 mmBERT를 이용하여 Validation Block의 Token Length를 계산한다.

Test와 Challenge Test는 현재 정책 결정 과정에서 사용하지 않는다.

In [16]:
VALIDATION_BLOCK_PATH = (
    BLOCK_OUTPUT_DIR
    / "validation_blocks.jsonl"
)


validation_blocks = load_jsonl(
    VALIDATION_BLOCK_PATH
)


print(
    f"Train blocks      : "
    f"{len(train_blocks):,}"
)

print(
    f"Validation blocks : "
    f"{len(validation_blocks):,}"
)

Train blocks      : 44,626
Validation blocks : 5,163

In [17]:
mmbert_tokenizer = (
    tokenizers["mmbert"]
)


validation_mmbert_lengths = (
    get_block_token_lengths(
        mmbert_tokenizer,
        validation_blocks,
    )
)

  5,120 / 5,163
  5,163 / 5,163

### 26.2 max_length 후보별 Overflow 분석

mmBERT의 최대 입력 길이는 8,192 Token이지만 실제 학습에서 항상 최대 길이를 사용할 필요는 없다.

Sequence가 길어질수록 계산량과 메모리 사용량이 증가하며, 증가 특성은 Backbone의 Attention 구조에 따라 달라진다.

현재 Dataset의 길이 분포를 고려하여 다음 세 값을 비교한다.

* 512
* 768
* 1024

각 후보에서 Train과 Validation Block 중 얼마나 많은 입력이 최대 길이를 초과하는지 확인한다.

In [18]:
MAX_LENGTH_CANDIDATES = [
    512,
    768,
    1024,
]


train_mmbert_lengths = (
    block_token_lengths[
        "mmbert"
    ]
)

In [19]:
overflow_rows = []


for split_name, lengths in [
    (
        "train",
        train_mmbert_lengths,
    ),
    (
        "validation",
        validation_mmbert_lengths,
    ),
]:
    for max_length in (
        MAX_LENGTH_CANDIDATES
    ):
        overflow_count = int(
            np.sum(
                lengths
                > max_length
            )
        )

        overflow_ratio = (
            overflow_count
            / len(lengths)
            * 100
        )

        overflow_rows.append(
            {
                "split":
                    split_name,

                "max_length":
                    max_length,

                "blocks":
                    len(lengths),

                "overflow_blocks":
                    overflow_count,

                "overflow_ratio":
                    overflow_ratio,
            }
        )


overflow_df = pd.DataFrame(
    overflow_rows
)


overflow_df[
    "overflow_ratio"
] = (
    overflow_df[
        "overflow_ratio"
    ]
    .round(3)
)


overflow_df

        split  max_length  blocks  overflow_blocks  overflow_ratio
0       train         512   44626             3758           8.421
1       train         768   44626              333           0.746
2       train        1024   44626                0           0.000
3  validation         512    5163              469           9.084
4  validation         768    5163               49           0.949
5  validation        1024    5163                0           0.000

### 26.3 Sliding Window 후보

실제 서비스에서는 현재 학습 Dataset보다 긴 입력이 들어올 수 있으므로 Sliding Window 기능은 유지한다.

현재 mmBERT에서 가장 긴 `PRIVATE_KEY` Entity는 최대 212 Token이었다.

따라서 우선 256 Token의 Overlap을 사용하는 Sliding Window를 분석한다.

비교 대상은 다음과 같다.

```
max_length=512,  stride=256
max_length=768,  stride=256
max_length=1024, stride=256
```

`stride`는 인접 Window 사이에서 중복해서 포함할 Token 수를 의미한다.

최종 값은 실제 Entity Fragment 분석 결과를 확인한 뒤 결정한다.

In [20]:
WINDOW_POLICY_CANDIDATES = [
    {
        "max_length": 512,
        "stride": 256,
    },
    {
        "max_length": 768,
        "stride": 256,
    },
    {
        "max_length": 1024,
        "stride": 256,
    },
]

### 26.4 Sliding Window Entity Fragment 분석

Sliding Window를 적용하면 하나의 Entity가 두 개 이상의 Window에 나타날 수 있다.

특히 Entity의 시작 지점이 포함되지 않고 중간 또는 끝 부분만 나타나는 Window가 발생할 수 있다.

이러한 Window에서 Entity Fragment를 그대로 `I-ENTITY`로 학습하면 모델이 주변 Context 없이 문자열 형태만으로 Entity를 판단하는 Shortcut을 학습할 위험이 있다.

따라서 다음 항목을 측정한다.

* 생성된 Window 수
* Overflow Block 수
* Entity와 겹치는 Window 수
* 일부만 포함된 Entity-Window Pair 수
* Entity 시작점이 없는 Fragment Pair 수
* 어떤 Window에도 Entity 전체가 포함되지 않는 Entity 수

정책 결정은 Train과 Validation만 사용한다.

In [21]:
def get_window_char_range(
    offsets,
):
    valid_offsets = [
        (start, end)
        for start, end
        in offsets
        if end > start
    ]

    if not valid_offsets:
        return None

    return (
        min(
            start
            for start, _
            in valid_offsets
        ),
        max(
            end
            for _, end
            in valid_offsets
        ),
    )

In [22]:
def analyze_window_policy(
    tokenizer,
    records,
    max_length,
    stride,
):
    total_blocks = len(
        records
    )

    overflow_blocks = 0

    total_windows = 0

    entity_window_pairs = 0

    partial_entity_pairs = 0

    start_missing_pairs = 0

    entities_without_full_window = 0

    total_entities = 0


    for record_index, record in enumerate(
        records,
        start=1,
    ):
        encoded = tokenizer(
            record["text"],
            add_special_tokens=True,
            truncation=True,
            max_length=max_length,
            stride=stride,
            return_overflowing_tokens=True,
            return_offsets_mapping=True,
            return_attention_mask=False,
            return_token_type_ids=False,
        )

        window_offsets = (
            encoded[
                "offset_mapping"
            ]
        )

        window_count = len(
            window_offsets
        )

        total_windows += (
            window_count
        )

        if window_count > 1:
            overflow_blocks += 1


        entity_full_coverage = [
            False
        ] * len(
            record["entities"]
        )


        for offsets in window_offsets:
            char_range = (
                get_window_char_range(
                    offsets
                )
            )

            if char_range is None:
                continue

            (
                window_start,
                window_end,
            ) = char_range


            for entity_index, entity in enumerate(
                record["entities"]
            ):
                entity_start = (
                    entity["start"]
                )

                entity_end = (
                    entity["end"]
                )


                overlaps = (
                    entity_start
                    < window_end
                    and entity_end
                    > window_start
                )

                if not overlaps:
                    continue


                entity_window_pairs += 1


                fully_contained = (
                    entity_start
                    >= window_start
                    and entity_end
                    <= window_end
                )

                if fully_contained:
                    entity_full_coverage[
                        entity_index
                    ] = True

                else:
                    partial_entity_pairs += 1


                start_missing = (
                    entity_start
                    < window_start
                    and entity_end
                    > window_start
                )

                if start_missing:
                    start_missing_pairs += 1


        total_entities += len(
            record["entities"]
        )

        entities_without_full_window += sum(
            not covered
            for covered
            in entity_full_coverage
        )


        if (
            record_index % 5000 == 0
            or record_index
            == len(records)
        ):
            print(
                f"  {record_index:,} / "
                f"{len(records):,}"
            )


    return {
        "blocks":
            total_blocks,

        "overflow_blocks":
            overflow_blocks,

        "overflow_ratio":
            (
                overflow_blocks
                / total_blocks
                * 100
            ),

        "windows":
            total_windows,

        "avg_windows":
            (
                total_windows
                / total_blocks
            ),

        "entity_window_pairs":
            entity_window_pairs,

        "partial_entity_pairs":
            partial_entity_pairs,

        "start_missing_pairs":
            start_missing_pairs,

        "start_missing_ratio":
            (
                start_missing_pairs
                / entity_window_pairs
                * 100
                if entity_window_pairs
                else 0
            ),

        "total_entities":
            total_entities,

        "entities_without_full_window":
            entities_without_full_window,
    }

In [23]:
development_blocks = (
    train_blocks
    + validation_blocks
)


print(
    f"Development blocks : "
    f"{len(development_blocks):,}"
)

Development blocks : 49,789

In [24]:
window_policy_results = []


for policy in (
    WINDOW_POLICY_CANDIDATES
):
    max_length = (
        policy[
            "max_length"
        ]
    )

    stride = (
        policy[
            "stride"
        ]
    )

    print(
        "\n"
        + "=" * 70
    )

    print(
        f"max_length={max_length}, "
        f"stride={stride}"
    )

    print(
        "=" * 70
    )

    result = (
        analyze_window_policy(
            mmbert_tokenizer,
            development_blocks,
            max_length=max_length,
            stride=stride,
        )
    )

    result[
        "max_length"
    ] = max_length

    result[
        "stride"
    ] = stride

    window_policy_results.append(
        result
    )

======================================================================
max_length=512, stride=256
======================================================================
  5,000 / 49,789
  10,000 / 49,789
  15,000 / 49,789
  20,000 / 49,789
  25,000 / 49,789
  30,000 / 49,789
  35,000 / 49,789
  40,000 / 49,789
  45,000 / 49,789
  49,789 / 49,789

======================================================================
max_length=768, stride=256
======================================================================
  5,000 / 49,789
  10,000 / 49,789
  15,000 / 49,789
  20,000 / 49,789
  25,000 / 49,789
  30,000 / 49,789
  35,000 / 49,789
  40,000 / 49,789
  45,000 / 49,789
  49,789 / 49,789

======================================================================
max_length=1024, stride=256
======================================================================
  5,000 / 49,789
  10,000 / 49,789
  15,000 / 49,789
  20,000 / 49,789
  25,000 / 49,789
  30,000 / 49,789
  35,000 / 49,789
  40,000 / 49,789
  45,000 / 49,789
  49,789 / 49,789

In [25]:
window_policy_df = pd.DataFrame(
    window_policy_results
)


display_columns = [
    "max_length",
    "stride",
    "blocks",
    "overflow_blocks",
    "overflow_ratio",
    "windows",
    "avg_windows",
    "entity_window_pairs",
    "partial_entity_pairs",
    "start_missing_pairs",
    "start_missing_ratio",
    "total_entities",
    "entities_without_full_window",
]


window_policy_summary = (
    window_policy_df[
        display_columns
    ]
    .copy()
)


window_policy_summary[
    [
        "overflow_ratio",
        "avg_windows",
        "start_missing_ratio",
    ]
] = (
    window_policy_summary[
        [
            "overflow_ratio",
            "avg_windows",
            "start_missing_ratio",
        ]
    ]
    .round(3)
)


window_policy_summary

,max_length,stride,blocks,overflow_blocks,overflow_ratio,windows,avg_windows,entity_window_pairs,partial_entity_pairs,start_missing_pairs,start_missing_ratio,total_entities,entities_without_full_window
0,512,256,49789,4227,8.490,54413,1.093,61830,0,0,0.0,61830,0
1,768,256,49789,382,0.767,50171,1.008,61830,0,0,0.0,61830,0
2,1024,256,49789,0,0.000,49789,1.000,61830,0,0,0.0,61830,0

### 26.6 max_length 및 Sliding Window 정책 결정

Train과 Validation Block을 대상으로 mmBERT의 입력 길이와 Sliding Window 동작을 분석하였다.

`max_length` 후보별 Overflow 비율은 다음과 같다.

| max_length | Train Overflow | Validation Overflow |
| ---: | ---: | ---: |
| 512 | 8.421% | 9.084% |
| 768 | 0.746% | 0.949% |
| 1024 | 0.000% | 0.000% |

512 Token을 사용하는 경우 약 8~9%의 Block에서 Sliding Window가 발생하였다.

768 Token에서는 Overflow 비율이 1% 미만으로 감소했지만 일부 Java Stack Trace는 여전히 여러 Window로 분리되었다.

1024 Token에서는 Train과 Validation의 모든 Block이 하나의 Window에 포함되었다.

또한 모든 Sliding Window 후보에서 다음 조건을 만족하였다.

- Entity가 일부만 포함된 Window 없음
- Entity 시작점이 없는 Fragment Window 없음
- 어떤 Window에도 Entity 전체가 포함되지 않는 경우 없음

현재 Dataset에서 가장 긴 Entity인 `PRIVATE_KEY`도 mmBERT 기준 최대 212 Token이므로 Entity 자체보다 긴 Java Stack Trace Context가 Sequence Length 증가의 주요 원인으로 판단된다.

따라서 Primary Backbone인 mmBERT의 입력 정책을 다음과 같이 결정한다.

    max_length = 1024
    stride = 256

`max_length=1024`를 사용하여 Train과 Validation에서는 가능한 한 Logical Block 전체의 문맥을 보존한다.

다만 실제 서비스에서는 현재 Dataset보다 긴 입력이 들어올 수 있으므로 Sliding Window 기능 자체는 유지한다.

`stride=256`은 현재 Train Dataset에서 가장 긴 Entity보다 큰 Overlap을 제공하여 긴 Entity가 Window 경계에 위치하는 경우에도 전체 Entity가 하나의 Window에 포함될 가능성을 높인다.

향후 실제 입력에서 Entity의 시작점이 포함되지 않은 Fragment Window가 발생하는 경우 해당 Entity Fragment Token은 학습 Label에서 `-100`으로 제외한다.

최종 평가는 Window 단위 Token Metric만을 기준으로 하지 않고, Window Prediction을 Block-level Character Span으로 복원한 뒤 Gold Character Span과 비교하는 방식을 Primary Evaluation으로 사용한다.

In [26]:
PRIMARY_BACKBONE = (
    "jhu-clsp/mmBERT-base"
)

MAX_LENGTH = 1024
STRIDE = 256


TOKENIZATION_POLICY = {
    "backbone":
        PRIMARY_BACKBONE,

    "max_length":
        MAX_LENGTH,

    "stride":
        STRIDE,

    "truncation":
        True,

    "return_overflowing_tokens":
        True,

    "return_offsets_mapping":
        True,
}


TOKENIZATION_POLICY

{'backbone': 'jhu-clsp/mmBERT-base',
 'max_length': 1024,
 'stride': 256,
 'truncation': True,
 'return_overflowing_tokens': True,
 'return_offsets_mapping': True}